Flow: RandomMeldableHeap< T, Predicate > Class Template Reference
RandomMeldableHeap< T, Predicate > Class Template Reference
#include <RandomMeldableHeap.h>
Classes
struct Node
Public Member Functions
RandomMeldableHeap ()
RandomMeldableHeap (const RandomMeldableHeap &)=delete
RandomMeldableHeap (RandomMeldableHeap &&heap)
RandomMeldableHeap & operator= (const RandomMeldableHeap &)=delete
RandomMeldableHeap & operator= (RandomMeldableHeap &&)=delete
~RandomMeldableHeap ()
void Merge (RandomMeldableHeap &&heap)
template<typename ... Args>
void Push (Args &&... args)
T & Top ()
const T & Top () const
void Pop ()
std::size_t Size () const
Static Private Member Functions
static Node * MergeRoots (Node *root0, Node *root1, Predicate p=Predicate())
Private Attributes
Node * root_
std::size_t _size
Static Private Attributes
static std::random_device rd {}
static std::bernoulli_distribution dis {}
Detailed Description
template<typename T, typename Predicate = std::greater<T>>
class RandomMeldableHeap< T, Predicate >
Definition at line 8 of file RandomMeldableHeap.h.
Constructor & Destructor Documentation
RandomMeldableHeap() [1/3]
template<typename T, typename Predicate = std::greater<T>> RandomMeldableHeap< T, Predicate >::RandomMeldableHeap () inline
Definition at line 29 of file RandomMeldableHeap.h.
: root_(), _size() {}
References _size, and root_.
Referenced by Merge(), operator=(), operator=(), RandomMeldableHeap(), and RandomMeldableHeap().
RandomMeldableHeap() [2/3]
template<typename T, typename Predicate = std::greater<T>> RandomMeldableHeap< T, Predicate >::RandomMeldableHeap (const RandomMeldableHeap< T, Predicate > &) delete
References RandomMeldableHeap().
RandomMeldableHeap() [3/3]
template<typename T, typename Predicate = std::greater<T>> RandomMeldableHeap< T, Predicate >::RandomMeldableHeap (RandomMeldableHeap< T, Predicate > && heap) inline
Definition at line 31 of file RandomMeldableHeap.h.
: root_(std::exchange(heap.root_, nullptr)), _size(std::exchange(heap._size, 0)) {}
References _size, RandomMeldableHeap(), and root_.
~RandomMeldableHeap()
template<typename T, typename Predicate = std::greater<T>> RandomMeldableHeap< T, Predicate >::~RandomMeldableHeap () inline
Definition at line 34 of file RandomMeldableHeap.h.
{
    delete root_;
  }
References root_.
Member Function Documentation
Merge()
template<typename T, typename Predicate = std::greater<T>> void RandomMeldableHeap< T, Predicate >::Merge (RandomMeldableHeap< T, Predicate > && heap) inline
Definition at line 57 of file RandomMeldableHeap.h.
{
    root_ = MergeRoots(root_, heap.root_);
    _size += heap._size;
    heap.root_ = nullptr;
    heap._size = 0;
  }
References _size, MergeRoots(), RandomMeldableHeap(), and root_.
MergeRoots()
template<typename T, typename Predicate = std::greater<T>> Node * RandomMeldableHeap< T, Predicate >::MergeRoots (Node * root0, Node * root1, Predicate p = Predicate()) inline static private
Definition at line 39 of file RandomMeldableHeap.h.
{
    if (!root0) {
      return root1;
    }
    if (!root1) {
      return root0;
    }
    if (p(root1->val_, root0->val_)) {
      std::swap(root0, root1);
    }
    Node** child = (dis(rd) ? &root0->left_ : &root0->right_);
    *child = MergeRoots(root1, *child);
    return root0;
  }
References dis, RandomMeldableHeap< T, Predicate >::Node::left_, MergeRoots(), rd, RandomMeldableHeap< T, Predicate >::Node::right_, and RandomMeldableHeap< T, Predicate >::Node::val_.
Referenced by Merge(), MergeRoots(), Pop(), and Push().
operator=() [1/2]
template<typename T, typename Predicate = std::greater<T>> RandomMeldableHeap & RandomMeldableHeap< T, Predicate >::operator= (const RandomMeldableHeap< T, Predicate > &) delete
References RandomMeldableHeap().
operator=() [2/2]
template<typename T, typename Predicate = std::greater<T>> RandomMeldableHeap & RandomMeldableHeap< T, Predicate >::operator= (RandomMeldableHeap< T, Predicate > &&) delete
References RandomMeldableHeap().
Pop()
template<typename T, typename Predicate = std::greater<T>> void RandomMeldableHeap< T, Predicate >::Pop () inline
Definition at line 80 of file RandomMeldableHeap.h.
             {
    assert(root_ && "pop from empty heap");
    Node* oldRoot = root_;
    root_ = MergeRoots(root_->left_, root_->right_);
    oldRoot->left_ = nullptr;
    oldRoot->right_ = nullptr;
    delete oldRoot;
    --_size;
  }
References _size, RandomMeldableHeap< T, Predicate >::Node::left_, MergeRoots(), RandomMeldableHeap< T, Predicate >::Node::right_, and root_.
Push()
template<typename T, typename Predicate = std::greater<T>> template<typename ... Args> void RandomMeldableHeap< T, Predicate >::Push (Args &&... args) inline
Definition at line 65 of file RandomMeldableHeap.h.
{
    root_ = MergeRoots(root_, new Node(T(std::forward<Args>(args)...)));
    ++_size;
  }
References _size, MergeRoots(), and root_.
Size()
template<typename T, typename Predicate = std::greater<T>> std::size_t RandomMeldableHeap< T, Predicate >::Size () const inline
Definition at line 91 of file RandomMeldableHeap.h.
{
    return _size;
  }
References _size.
Top() [1/2]
template<typename T, typename Predicate = std::greater<T>> T & RandomMeldableHeap< T, Predicate >::Top () inline
Definition at line 70 of file RandomMeldableHeap.h.
           {
    assert(_size >= 0 && "access empty heap top");
    return root_->val_;
  }
References _size, and root_.
Top() [2/2]
template<typename T, typename Predicate = std::greater<T>> const T & RandomMeldableHeap< T, Predicate >::Top () const inline
Definition at line 75 of file RandomMeldableHeap.h.
                       {
    assert(_size >= 0 && "access empty heap top");
    return root_->val_;
  }
References _size, and root_.
Member Data Documentation
_size
template<typename T, typename Predicate = std::greater<T>> std::size_t RandomMeldableHeap< T, Predicate >::_size private
Definition at line 26 of file RandomMeldableHeap.h.
Referenced by Merge(), Pop(), Push(), RandomMeldableHeap(), RandomMeldableHeap(), Size(), Top(), and Top().
dis
template<typename T, typename Predicate = std::greater<T>> std::bernoulli_distribution RandomMeldableHeap< T, Predicate >::dis {} inline static private
Definition at line 97 of file RandomMeldableHeap.h.
{};
Referenced by MergeRoots().
rd
template<typename T, typename Predicate = std::greater<T>> std::random_device RandomMeldableHeap< T, Predicate >::rd {} inline static private
Definition at line 96 of file RandomMeldableHeap.h.
{};
Referenced by MergeRoots().
root_
template<typename T, typename Predicate = std::greater<T>> Node* RandomMeldableHeap< T, Predicate >::root_ private
Definition at line 25 of file RandomMeldableHeap.h.
Referenced by Merge(), Pop(), Push(), RandomMeldableHeap(), RandomMeldableHeap(), Top(), Top(), and ~RandomMeldableHeap().
The documentation for this class was generated from the following file:
C:/Users/evanh/Desktop/DataStructure/DataStructure/RandomMeldableHeap.h