Flow: flow::DebugClass Class Reference
flow::DebugClass Class Reference
Debug class that tracks object's copy/move opeartions. Note that some of the operations may get optimized away with optimization on.
#include <flow_debug_memory.h>
Public Member Functions
DebugClass ()
DebugClass (const DebugClass &rhs)
DebugClass (DebugClass &&rhs) noexcept
~DebugClass ()
DebugClass & operator= (const DebugClass &rhs)
DebugClass & operator= (DebugClass &&rhs) noexcept
Private Attributes
std::shared_ptr< std::size_t > copyCounter_
std::size_t copies_
std::size_t id_
Static Private Attributes
static std::size_t globalId = 0
Friends
std::ostream & operator<< (std::ostream &out, const DebugClass &obj)
Detailed Description
Debug class that tracks object's copy/move opeartions. Note that some of the operations may get optimized away with optimization on.
Definition at line 27 of file flow_debug_memory.h.
Constructor & Destructor Documentation
DebugClass() [1/3]
flow::DebugClass::DebugClass () inline
Definition at line 33 of file flow_debug_memory.h.
      : copyCounter_(std::make_shared<std::size_t>(0)),
        copies_(0),
        id_(globalId++) {
      std::cout << std::format("default_ctor id {}, copies {}\n", id_, copies_);
    }
References copies_, copyCounter_, globalId, and id_.
Referenced by DebugClass(), DebugClass(), operator<<, operator=(), and operator=().
DebugClass() [2/3]
flow::DebugClass::DebugClass (const DebugClass & rhs) inline
Definition at line 40 of file flow_debug_memory.h.
      : copyCounter_(rhs.copyCounter_),
        copies_(++(*copyCounter_)),
        id_(rhs.id_) {
      std::cout << std::format("copy_ctor id {}, copies {}\n", id_, copies_);
    }
References copies_, copyCounter_, DebugClass(), and id_.
DebugClass() [3/3]
flow::DebugClass::DebugClass (DebugClass && rhs) inline noexcept
Definition at line 48 of file flow_debug_memory.h.
      : copyCounter_(std::move(rhs.copyCounter_)),
        copies_(rhs.copies_),
        id_(rhs.id_) {
      std::cout << std::format("move_ctor id {}, copies {}\n", id_, copies_);
    }
References copies_, DebugClass(), and id_.
~DebugClass()
flow::DebugClass::~DebugClass () inline
Definition at line 55 of file flow_debug_memory.h.
                  {
      std::cout << std::format("dtor id {}, copies {}\n", id_, copies_);
    }
References copies_, and id_.
Member Function Documentation
operator=() [1/2]
DebugClass & flow::DebugClass::operator= (const DebugClass & rhs) inline
Definition at line 59 of file flow_debug_memory.h.
{
      copyCounter_ = rhs.copyCounter_;
      copies_ = ++(*copyCounter_);
      id_ = rhs.id_;
      std::cout << std::format("copy_op id {}, copies {}\n", id_, copies_);
    }
References copies_, copyCounter_, DebugClass(), and id_.
operator=() [2/2]
DebugClass & flow::DebugClass::operator= (DebugClass && rhs) inline noexcept
Definition at line 66 of file flow_debug_memory.h.
{
      copyCounter_ = std::move(rhs.copyCounter_);
      copies_ = rhs.copies_;
      id_ = rhs.id_;
      std::cout << std::format("move_op id {}, copies {}\n", id_, copies_);
    }
References copies_, copyCounter_, DebugClass(), and id_.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const DebugClass & obj) friend
Definition at line 76 of file flow_debug_memory.h.
{
      out << std::format("{{id: {}, copies: {}}}", obj.id_, obj.copies_);
      return out;
    }
References copies_, DebugClass(), and id_.
Member Data Documentation
copies_
std::size_t flow::DebugClass::copies_ private
Definition at line 29 of file flow_debug_memory.h.
Referenced by DebugClass(), DebugClass(), DebugClass(), operator<<, operator=(), operator=(), and ~DebugClass().
copyCounter_
std::shared_ptr<std::size_t> flow::DebugClass::copyCounter_ private
Definition at line 28 of file flow_debug_memory.h.
Referenced by DebugClass(), DebugClass(), operator=(), and operator=().
globalId
std::size_t flow::DebugClass::globalId = 0 inline static private
Definition at line 74 of file flow_debug_memory.h.
Referenced by DebugClass().
id_
std::size_t flow::DebugClass::id_ private
Definition at line 30 of file flow_debug_memory.h.
Referenced by DebugClass(), DebugClass(), DebugClass(), operator<<, operator=(), operator=(), and ~DebugClass().
The documentation for this class was generated from the following file:
flow_debug_memory.h