Flow: flow::MemoryResource Class Reference
flow::MemoryResource Class Reference abstract
A memory resource holder interface for the PolymorphicAllocator. Responsible for allocate and deallocate raw memory.
#include <flow_memory_resource.h>
Public Member Functions
virtual ~MemoryResource ()=default
void * allocate (std::size_t bytes, std::size_t alignment=alignof(std::max_align_t))
void deallocate (void *address, std::size_t bytes, std::size_t alignment=alignof(std::max_align_t))
Protected Member Functions
virtual void * allocateImp (std::size_t bytes, std::size_t alignment)=0
virtual void deallocateImp (void *address, std::size_t bytes, std::size_t alignment)=0
Detailed Description
A memory resource holder interface for the PolymorphicAllocator. Responsible for allocate and deallocate raw memory.
Definition at line 9 of file flow_memory_resource.h.
Constructor & Destructor Documentation
~MemoryResource()
virtual flow::MemoryResource::~MemoryResource () virtual default
Member Function Documentation
allocate()
void * flow::MemoryResource::allocate (std::size_t bytes, std::size_t alignment = alignof(std::max_align_t)) inline
Definition at line 13 of file flow_memory_resource.h.
{
      return allocateImp(bytes, alignment);
    }
References allocateImp().
allocateImp()
virtual void * flow::MemoryResource::allocateImp (std::size_t bytes, std::size_t alignment) protected pure virtual
Implemented in flow::ArenaMemoryResource, flow::DefaultMemoryResource, flow::PoolMemoryResource, and flow::StackMemoryResource.
Referenced by allocate().
deallocate()
void flow::MemoryResource::deallocate (void * address, std::size_t bytes, std::size_t alignment = alignof(std::max_align_t)) inline
Definition at line 17 of file flow_memory_resource.h.
{
      deallocateImp(address, bytes, alignment);
    }
References deallocateImp().
deallocateImp()
virtual void flow::MemoryResource::deallocateImp (void * address, std::size_t bytes, std::size_t alignment) protected pure virtual
Implemented in flow::ArenaMemoryResource, flow::DefaultMemoryResource, flow::PoolMemoryResource, and flow::StackMemoryResource.
Referenced by deallocate().
The documentation for this class was generated from the following file:
flow_memory_resource.h