Flow: flow::IntegralIterator< T > Class Template Reference
flow::IntegralIterator< T > Class Template Reference
An iterator that can iterate through a range of integer. Useful when the search space is too big to fit into a container.
#include <flow_integral_iterator.h>
Public Types
using value_type = T
using difference_type = std::ptrdiff_t
using reference = T
using pointer = void
using iterator_category = std::random_access_iterator_tag
Public Member Functions
constexpr IntegralIterator (T value) noexcept
constexpr reference operator* () const noexcept
constexpr IntegralIterator & operator++ () noexcept
constexpr IntegralIterator operator++ (int) noexcept
constexpr IntegralIterator & operator-- () noexcept
constexpr IntegralIterator operator-- (int) noexcept
constexpr IntegralIterator & operator+= (difference_type n) noexcept
constexpr IntegralIterator & operator-= (difference_type n) noexcept
constexpr reference operator[] (difference_type n) const noexcept
constexpr difference_type operator- (const IntegralIterator &rhs) const noexcept
constexpr auto operator<=> (const IntegralIterator &) const =default
Private Attributes
T value_
Friends
void swap (IntegralIterator &lhs, IntegralIterator &rhs) noexcept
Detailed Description
template<std::integral T>
class flow::IntegralIterator< T >
An iterator that can iterate through a range of integer. Useful when the search space is too big to fit into a container.
Definition at line 10 of file flow_integral_iterator.h.
Member Typedef Documentation
difference_type
template<std::integral T> using flow::IntegralIterator< T >::difference_type = std::ptrdiff_t
Definition at line 15 of file flow_integral_iterator.h.
iterator_category
template<std::integral T> using flow::IntegralIterator< T >::iterator_category = std::random_access_iterator_tag
Definition at line 18 of file flow_integral_iterator.h.
pointer
template<std::integral T> using flow::IntegralIterator< T >::pointer = void
Definition at line 17 of file flow_integral_iterator.h.
reference
template<std::integral T> using flow::IntegralIterator< T >::reference = T
Definition at line 16 of file flow_integral_iterator.h.
value_type
template<std::integral T> using flow::IntegralIterator< T >::value_type = T
Definition at line 14 of file flow_integral_iterator.h.
Constructor & Destructor Documentation
IntegralIterator()
template<std::integral T> flow::IntegralIterator< T >::IntegralIterator (T value) inline explicit constexpr noexcept
Definition at line 20 of file flow_integral_iterator.h.
: value_(value) {}
Referenced by operator++(), operator++(), operator+=(), operator-(), operator--(), operator--(), operator-=(), operator<=>(), and swap.
Member Function Documentation
operator*()
template<std::integral T> reference flow::IntegralIterator< T >::operator* () const inline constexpr noexcept
Definition at line 22 of file flow_integral_iterator.h.
{
      return value_;
    }
References value_.
operator++() [1/2]
template<std::integral T> IntegralIterator & flow::IntegralIterator< T >::operator++ () inline constexpr noexcept
Definition at line 26 of file flow_integral_iterator.h.
{
      ++value_;
      return *this;
    }
References IntegralIterator(), and value_.
operator++() [2/2]
template<std::integral T> IntegralIterator flow::IntegralIterator< T >::operator++ (int) inline constexpr noexcept
Definition at line 31 of file flow_integral_iterator.h.
{
      IntegralIterator tmp = *this;
      ++*this;
      return tmp;
    }
References IntegralIterator().
operator+=()
template<std::integral T> IntegralIterator & flow::IntegralIterator< T >::operator+= (difference_type n) inline constexpr noexcept
Definition at line 48 of file flow_integral_iterator.h.
{
      value_ += static_cast<T>(n);
      return *this;
    }
References IntegralIterator(), and value_.
operator-()
template<std::integral T> difference_type flow::IntegralIterator< T >::operator- (const IntegralIterator< T > & rhs) const inline constexpr noexcept
Definition at line 62 of file flow_integral_iterator.h.
{
      return static_cast<difference_type>(value_) - static_cast<difference_type>(rhs.value_);
    }
References IntegralIterator(), and value_.
operator--() [1/2]
template<std::integral T> IntegralIterator & flow::IntegralIterator< T >::operator-- () inline constexpr noexcept
Definition at line 37 of file flow_integral_iterator.h.
{
      --value_;
      return *this;
    }
References IntegralIterator(), and value_.
operator--() [2/2]
template<std::integral T> IntegralIterator flow::IntegralIterator< T >::operator-- (int) inline constexpr noexcept
Definition at line 42 of file flow_integral_iterator.h.
{
      IntegralIterator tmp = *this;
      --*this;
      return tmp;
    }
References IntegralIterator().
operator-=()
template<std::integral T> IntegralIterator & flow::IntegralIterator< T >::operator-= (difference_type n) inline constexpr noexcept
Definition at line 53 of file flow_integral_iterator.h.
{
      value_ -= static_cast<T>(n);
      return *this;
    }
References IntegralIterator(), and value_.
operator<=>()
template<std::integral T> auto flow::IntegralIterator< T >::operator<=> (const IntegralIterator< T > &) const constexpr default
References IntegralIterator().
operator[]()
template<std::integral T> reference flow::IntegralIterator< T >::operator[] (difference_type n) const inline constexpr noexcept
Definition at line 58 of file flow_integral_iterator.h.
{
      return value_ + static_cast<reference>(n);
    }
References value_.
Friends And Related Symbol Documentation
swap
template<std::integral T> void swap (IntegralIterator< T > & lhs, IntegralIterator< T > & rhs) friend
Definition at line 68 of file flow_integral_iterator.h.
{
      using std::swap;
      swap(lhs.value_, rhs.value_);
    }
References IntegralIterator(), and swap.
Referenced by swap.
Member Data Documentation
value_
template<std::integral T> T flow::IntegralIterator< T >::value_ private
Definition at line 11 of file flow_integral_iterator.h.
Referenced by operator*(), operator++(), operator+=(), operator-(), operator--(), operator-=(), and operator[]().
The documentation for this class was generated from the following file:
flow_integral_iterator.h