Flow: BinomialHeap< T, Predicate > Class Template Reference
BinomialHeap< T, Predicate > Class Template Reference
#include <BinomialHeap.h>
Classes
class FlagTree
Public Member Functions
BinomialHeap ()
BinomialHeap (const BinomialHeap &rhs)
BinomialHeap (BinomialHeap &&rhs) noexcept
~BinomialHeap ()
BinomialHeap & operator= (BinomialHeap rhs)
std::size_t Size () const
bool Empty () const
const T & Top () const
T & Top ()
template<typename... Args>
void Push (Args &&... args)
void Merge (BinomialHeap heap)
void Pop ()
void Debug () const
Private Member Functions
void MergeToHeight (FlagTree *tree0, int height)
int GetMaxIndex () const
Private Attributes
std::vector< FlagTree * > _trees
std::size_t _size
Friends
void swap (BinomialHeap &lhs, BinomialHeap &rhs)
Detailed Description
template<typename T, typename Predicate>
class BinomialHeap< T, Predicate >
Definition at line 18 of file BinomialHeap.h.
Constructor & Destructor Documentation
BinomialHeap() [1/3]
template<typename T, typename Predicate> BinomialHeap< T, Predicate >::BinomialHeap () inline
Definition at line 57 of file BinomialHeap.h.
                 :
    _trees(), _size(0) {
  }
References _size, and _trees.
Referenced by BinomialHeap(), BinomialHeap(), Merge(), operator=(), and swap.
BinomialHeap() [2/3]
template<typename T, typename Predicate> BinomialHeap< T, Predicate >::BinomialHeap (const BinomialHeap< T, Predicate > & rhs) inline
Definition at line 61 of file BinomialHeap.h.
                                        :
    _trees(rhs._trees.size()), _size(rhs._size) {
    for (int h = 0; h < rhs._trees.size(); ++h) {
      if (rhs._trees[h]) {
        FlagTree* t = rhs._trees[h];
        _trees[h] = new FlagTree(*t);
      }
    }
  }
References _size, _trees, and BinomialHeap().
BinomialHeap() [3/3]
template<typename T, typename Predicate> BinomialHeap< T, Predicate >::BinomialHeap (BinomialHeap< T, Predicate > && rhs) inline noexcept
Definition at line 71 of file BinomialHeap.h.
                                            :
    _trees(std::move(rhs._trees)), _size(std::exchange(rhs._size, 0)) {
  }
References BinomialHeap().
~BinomialHeap()
template<typename T, typename Predicate> BinomialHeap< T, Predicate >::~BinomialHeap () inline
Definition at line 75 of file BinomialHeap.h.
                  {
    for (const FlagTree* tree : _trees) {
      delete tree;
    }
  }
References _trees.
Member Function Documentation
Debug()
template<typename T, typename Predicate> void BinomialHeap< T, Predicate >::Debug () const inline
Definition at line 138 of file BinomialHeap.h.
                     {
    #ifdef _DEBUG
    std::cout << "size: " << _size << '\n';
    for (const FlagTree* tree : _trees) {
      Print("", tree, false);
    }
    #endif
  }
References _size, and _trees.
Empty()
template<typename T, typename Predicate> bool BinomialHeap< T, Predicate >::Empty () const inline
Definition at line 90 of file BinomialHeap.h.
                     {
    return _size == 0;
  }
References _size.
GetMaxIndex()
template<typename T, typename Predicate> int BinomialHeap< T, Predicate >::GetMaxIndex () const inline private
Definition at line 171 of file BinomialHeap.h.
{
    assert(_size != 0);
    const Predicate cmp{};
    int m = -1;
    for (int h = 0; h < _trees.size(); ++h) {
      if (_trees[h] && (m == -1 || cmp(_trees[h]->_data, _trees[m]->_data))) {
        m = h;
      }
    }
    return m;
  }
References _size, and _trees.
Referenced by Pop(), Top(), and Top().
Merge()
template<typename T, typename Predicate> void BinomialHeap< T, Predicate >::Merge (BinomialHeap< T, Predicate > heap) inline
Definition at line 108 of file BinomialHeap.h.
{
    for (int h = 0; h < heap._trees.size(); ++h) {
      if (FlagTree* tree = heap._trees[h]; tree) {
        MergeToHeight(tree, h);
      }
    }
    _size += heap._size;
    heap._trees.clear();
    heap._size = 0;
  }
References _size, _trees, BinomialHeap(), and MergeToHeight().
MergeToHeight()
template<typename T, typename Predicate> void BinomialHeap< T, Predicate >::MergeToHeight (FlagTree * tree0, int height) inline private
Definition at line 148 of file BinomialHeap.h.
{
    const Predicate cmp{};
    while (true) {
      if (height >= _trees.size()) {
        _trees.resize(height + 1);
        break;
      }
      if (FlagTree* tree1 = _trees[height]; tree1) {
        if (cmp(tree1->_data, tree0->_data)) {
          std::swap(tree0, tree1);
        }
        tree1->_right = tree0->_left;
        tree0->_left = tree1;
        _trees[height++] = nullptr;
      } else {
        break;
      }
    }
    _trees[height] = tree0;
  }
References BinomialHeap< T, Predicate >::FlagTree::_data, BinomialHeap< T, Predicate >::FlagTree::_left, and _trees.
Referenced by Merge(), Pop(), and Push().
operator=()
template<typename T, typename Predicate> BinomialHeap & BinomialHeap< T, Predicate >::operator= (BinomialHeap< T, Predicate > rhs) inline
Definition at line 81 of file BinomialHeap.h.
{
    swap(*this, rhs);
    return *this;
  }
References BinomialHeap(), and swap.
Pop()
template<typename T, typename Predicate> void BinomialHeap< T, Predicate >::Pop () inline
Definition at line 120 of file BinomialHeap.h.
             {
    int h = GetMaxIndex();
    FlagTree* tree = _trees[h]->_left;
    _trees[h]->_left = nullptr;
    delete _trees[h];
    _trees[h] = nullptr;
    while (tree) {
      --h;
      FlagTree* const next = tree->_right;
      tree->_right = nullptr;
      MergeToHeight(tree, h);
      tree = next;
    }
    --_size;
  }
References BinomialHeap< T, Predicate >::FlagTree::_right, _size, _trees, GetMaxIndex(), and MergeToHeight().
Push()
template<typename T, typename Predicate> template<typename... Args> void BinomialHeap< T, Predicate >::Push (Args &&... args) inline
Definition at line 103 of file BinomialHeap.h.
{
    MergeToHeight(new FlagTree(std::forward<Args>(args)...), 0);
    ++_size;
  }
References _size, and MergeToHeight().
Size()
template<typename T, typename Predicate> std::size_t BinomialHeap< T, Predicate >::Size () const inline
Definition at line 86 of file BinomialHeap.h.
{
    return _size;
  }
References _size.
Top() [1/2]
template<typename T, typename Predicate> T & BinomialHeap< T, Predicate >::Top () inline
Definition at line 98 of file BinomialHeap.h.
           {
    return _trees[GetMaxIndex()]->_data;
  }
References _trees, and GetMaxIndex().
Top() [2/2]
template<typename T, typename Predicate> const T & BinomialHeap< T, Predicate >::Top () const inline
Definition at line 94 of file BinomialHeap.h.
                       {
    return _trees[GetMaxIndex()]->_data;
  }
References _trees, and GetMaxIndex().
Friends And Related Symbol Documentation
swap
template<typename T, typename Predicate> void swap (BinomialHeap< T, Predicate > & lhs, BinomialHeap< T, Predicate > & rhs) friend
Definition at line 197 of file BinomialHeap.h.
{
  using std::swap;
  swap(lhs._trees, rhs._trees);
  swap(lhs._size, rhs._size);
}
References _size, _trees, BinomialHeap(), and swap().
Referenced by operator=().
Member Data Documentation
_size
template<typename T, typename Predicate> std::size_t BinomialHeap< T, Predicate >::_size private
Definition at line 54 of file BinomialHeap.h.
Referenced by BinomialHeap(), BinomialHeap(), Debug(), Empty(), GetMaxIndex(), Merge(), Pop(), Push(), Size(), and swap.
_trees
template<typename T, typename Predicate> std::vector<FlagTree*> BinomialHeap< T, Predicate >::_trees private
Definition at line 53 of file BinomialHeap.h.
Referenced by BinomialHeap(), BinomialHeap(), Debug(), GetMaxIndex(), Merge(), MergeToHeight(), Pop(), swap, Top(), Top(), and ~BinomialHeap().
The documentation for this class was generated from the following file:
C:/Users/evanh/Desktop/DataStructure/DataStructure/BinomialHeap.h