Flow: Trie< T > Class Template Reference
Trie< T > Class Template Reference
#include <Trie.h>
Classes
class Node
Public Member Functions
Trie ()
Node * Find (const T *arr, std::size_t len)
const Node * Find (const T *arr, std::size_t len) const
bool Contain (const T *arr, std::size_t len) const
bool ContainPrefix (const T *arr, std::size_t len) const
void Push (const T *arr, std::size_t len)
void Erase (const T *arr, std::size_t len)
std::vector< std::vector< T > > GetAll () const
Static Private Member Functions
static void Walk (std::vector< std::vector< T > > &res, std::vector< T > &seq, const Trie< T >::Node &curr)
Private Attributes
Node root_
Detailed Description
template<typename T>
class Trie< T >
Definition at line 7 of file Trie.h.
Constructor & Destructor Documentation
Trie()
template<typename T> Trie< T >::Trie ()
Definition at line 38 of file Trie.h.
: root_() {}
References root_.
Referenced by Find().
Member Function Documentation
Contain()
template<typename T> bool Trie< T >::Contain (const T * arr, std::size_t len) const
Definition at line 62 of file Trie.h.
{
  const typename Trie<T>::Node* res = Find(arr, len);
  return res != nullptr && res->is_end_;
}
References Find(), and Trie< T >::Node::is_end_.
ContainPrefix()
template<typename T> bool Trie< T >::ContainPrefix (const T * arr, std::size_t len) const
Definition at line 68 of file Trie.h.
{
  const typename Trie<T>::Node* res = Find(arr, len);
  return res != nullptr;
}
References Find().
Erase()
template<typename T> void Trie< T >::Erase (const T * arr, std::size_t len)
Definition at line 83 of file Trie.h.
{
  std::vector<Trie<T>::Node*> stk;
  Trie<T>::Node* curr = &root_;
  for (std::size_t i = 0; i < len; ++i) {
    auto res = curr->child_.find(arr[i]);
    if (res == curr->child_.end()) return;
    stk.push_back(curr);
    curr = &res->second;
  }
  //check if such string is in the trie
  if (!curr->is_end_) return;
  curr->is_end_ = false;
  for (int i = int(len) - 1; i >= 0; --i) {
    //erase from the parent if node is not ended and no child
    if (curr->child_.empty() && !curr->is_end_) {
      stk[i]->child_.erase(arr[i]);
      curr = stk[i];
    } else {
      break;
    }
  }
}
References Trie< T >::Node::child_, Trie< T >::Node::is_end_, and root_.
Find() [1/2]
template<typename T> Trie< T >::Node * Trie< T >::Find (const T * arr, std::size_t len)
Definition at line 45 of file Trie.h.
{
  return const_cast<Trie<T>::Node*>(static_cast<const Trie<T>&>(*this).Find(arr, len));
}
References Trie().
Referenced by Contain(), and ContainPrefix().
Find() [2/2]
template<typename T> const Trie< T >::Node * Trie< T >::Find (const T * arr, std::size_t len) const
Definition at line 50 of file Trie.h.
{
  const typename Trie<T>::Node* curr = &root_;
  for (std::size_t i = 0; i < len; ++i) {
    const auto res = curr->child_.find(arr[i]);
    if (res == curr->child_.end()) return nullptr;
    curr = &res->second;
  }
  return curr;
}
References Trie< T >::Node::child_, and root_.
GetAll()
template<typename T> std::vector< std::vector< T > > Trie< T >::GetAll () const
Definition at line 113 of file Trie.h.
{
  std::vector<std::vector<T>> res;
  std::vector<T> seq;
  Walk(res, seq, root_);
  return res;
}
References root_, and Walk().
Push()
template<typename T> void Trie< T >::Push (const T * arr, std::size_t len)
Definition at line 74 of file Trie.h.
{
  Trie<T>::Node* curr = &root_;
  for (std::size_t i = 0; i < len; ++i) {
    curr = &curr->child_[arr[i]];
  }
  curr->is_end_ = true;
}
References Trie< T >::Node::child_, Trie< T >::Node::is_end_, and root_.
Walk()
template<typename T> void Trie< T >::Walk (std::vector< std::vector< T > > & res, std::vector< T > & seq, const Trie< T >::Node & curr) static private
Definition at line 123 of file Trie.h.
{
  for (const auto& child : curr.child_) {
    //extend the trie sequence
    seq.push_back(child.first);
    if (child.second.is_end_) {
      res.push_back(seq);
    }
    //keep walking down the tree
    Walk(res, seq, child.second);
    //go back to the parent
    seq.pop_back();
  }
}
References Trie< T >::Node::child_, and Walk().
Referenced by GetAll(), and Walk().
Member Data Documentation
root_
template<typename T> Node Trie< T >::root_ private
Definition at line 18 of file Trie.h.
Referenced by Erase(), Find(), GetAll(), Push(), and Trie().
The documentation for this class was generated from the following file:
C:/Users/evanh/Desktop/DataStructure/DataStructure/Trie.h