Flow: AVLTree< T > Class Template Reference
AVLTree< T > Class Template Reference
#include <AVLTree.h>
Classes
class Node
Public Member Functions
AVLTree ()
AVLTree (const AVLTree &tree)
AVLTree (AVLTree &&tree) noexcept
~AVLTree ()
AVLTree & operator= (AVLTree rhs) noexcept
bool Empty () const
int Size () const
T * Min ()
T * Max ()
const T * Min () const
const T * Max () const
void Print () const
T * Find (const T &key)
const T * Find (const T &key) const
template<typename Arg>
void Push (Arg &&key)
void Erase (const T &key)
Private Attributes
int _size
Node * root_
Friends
void swap (AVLTree &lhs, AVLTree &rhs)
Detailed Description
template<typename T>
class AVLTree< T >
Definition at line 20 of file AVLTree.h.
Constructor & Destructor Documentation
AVLTree() [1/3]
template<typename T> AVLTree< T >::AVLTree ()
Definition at line 62 of file AVLTree.h.
: _size(0), root_(nullptr) {}
References _size, and root_.
Referenced by AVLTree(), AVLTree(), Find(), Max(), Min(), operator=(), and swap.
AVLTree() [2/3]
template<typename T> AVLTree< T >::AVLTree (const AVLTree< T > & tree)
Definition at line 65 of file AVLTree.h.
                                       : _size(tree._size) {
  if (tree.root_) {
    root_ = new Node(*tree.root_);
  }
}
References _size, AVLTree(), and root_.
AVLTree() [3/3]
template<typename T> AVLTree< T >::AVLTree (AVLTree< T > && tree) noexcept
Definition at line 72 of file AVLTree.h.
: _size(tree._size), root_(std::exchange(tree.root_, nullptr)) {}
References _size, AVLTree(), and root_.
~AVLTree()
template<typename T> AVLTree< T >::~AVLTree ()
Definition at line 75 of file AVLTree.h.
                     {
  delete this->root_;
}
References root_.
Member Function Documentation
Empty()
template<typename T> bool AVLTree< T >::Empty () const
Definition at line 86 of file AVLTree.h.
{
  return _size == 0;
}
References _size.
Erase()
template<typename T> void AVLTree< T >::Erase (const T & key)
Definition at line 152 of file AVLTree.h.
{
  Node::Erase(&root_, root_, key);
}
References AVLTree< T >::Node::Erase(), and root_.
Referenced by AVLTree< T >::Node::Erase().
Find() [1/2]
template<typename T> T * AVLTree< T >::Find (const T & key)
Definition at line 141 of file AVLTree.h.
{
  return const_cast<T*>(static_cast<const AVLTree<T>&>(*this).Find(key));
}
References AVLTree().
Referenced by AVLTree< T >::Node::Find(), and AVLTree< T >::Node::Find().
Find() [2/2]
template<typename T> const T * AVLTree< T >::Find (const T & key) const
Definition at line 136 of file AVLTree.h.
{
  return Node::Find(root_, key);
}
References AVLTree< T >::Node::Find(), and root_.
Max() [1/2]
template<typename T> T * AVLTree< T >::Max ()
Definition at line 111 of file AVLTree.h.
                   {
  return const_cast<T*>(static_cast<const AVLTree<T>&>(*this).Max());
}
References AVLTree().
Max() [2/2]
template<typename T> const T * AVLTree< T >::Max () const
Definition at line 106 of file AVLTree.h.
{
  return (root_ ? root_->Max() : nullptr);
}
References root_.
Min() [1/2]
template<typename T> T * AVLTree< T >::Min ()
Definition at line 101 of file AVLTree.h.
                   {
  return const_cast<T*>(static_cast<const AVLTree<T>&>(*this).Min());
}
References AVLTree().
Min() [2/2]
template<typename T> const T * AVLTree< T >::Min () const
Definition at line 96 of file AVLTree.h.
{
  return (root_ ? root_->Min() : nullptr);
}
References root_.
operator=()
template<typename T> AVLTree< T > & AVLTree< T >::operator= (AVLTree< T > rhs) noexcept
Definition at line 80 of file AVLTree.h.
{
  swap(*this, tree);
  return *this;
}
References AVLTree(), and swap().
Print()
template<typename T> void AVLTree< T >::Print () const
Definition at line 116 of file AVLTree.h.
{
  if (!this->root_) {
    std::cout << "Empty Tree\n";
    return;
  }
  int max_depth = 0;
  int max_breadth = 0;
  std::string graph_str = this->root_->Print(0, max_depth, max_breadth);
  std::string line_break(max_depth * 6, '-');
  std::cout << '\n'
    << graph_str << '\n'
    << line_break << '\n'
    << "Max Depth: " << max_depth << '\n'
    << "Max Breadth: " << max_breadth << '\n';
}
References root_.
Push()
template<typename T> template<typename Arg> void AVLTree< T >::Push (Arg && key)
Definition at line 147 of file AVLTree.h.
{
  Node::Push(&root_, root_, std::forward<Arg>(key));
}
References AVLTree< T >::Node::Push(), and root_.
Referenced by AVLTree< T >::Node::Push().
Size()
template<typename T> int AVLTree< T >::Size () const
Definition at line 91 of file AVLTree.h.
{
  return _size;
}
References _size.
Friends And Related Symbol Documentation
swap
template<typename T> void swap (AVLTree< T > & lhs, AVLTree< T > & rhs) friend
Definition at line 55 of file AVLTree.h.
{
  using std::swap;
  swap(lhs._size, rhs._size);
  swap(lhs.root_, rhs.root_);
}
References _size, AVLTree(), root_, and swap().
Member Data Documentation
_size
template<typename T> int AVLTree< T >::_size private
Definition at line 24 of file AVLTree.h.
Referenced by AVLTree(), AVLTree(), AVLTree(), Empty(), Size(), and swap.
root_
template<typename T> Node* AVLTree< T >::root_ private
Definition at line 25 of file AVLTree.h.
Referenced by AVLTree(), AVLTree(), AVLTree(), Erase(), Find(), Max(), Min(), Print(), Push(), swap, and ~AVLTree().
The documentation for this class was generated from the following file:
AVLTree.h