Flow: BinomialHeap< T, Predicate >::FlagTree Class Reference
BinomialHeap< T, Predicate >::FlagTree Class Reference
Private Member Functions
template<typename ... Args>
FlagTree (Args &&... args)
FlagTree (const FlagTree &rhs)
FlagTree (FlagTree &rhs)
FlagTree (FlagTree &&rhs) noexcept
~FlagTree ()
FlagTree & operator= (const FlagTree &rhs)=delete
FlagTree & operator= (FlagTree &&rhs)=delete
Private Attributes
T _data
FlagTree * _left
FlagTree * _right
Friends
class BinomialHeap
Detailed Description
template<typename T, typename Predicate>
class BinomialHeap< T, Predicate >::FlagTree
Definition at line 19 of file BinomialHeap.h.
Constructor & Destructor Documentation
FlagTree() [1/4]
template<typename T, typename Predicate> template<typename ... Args> BinomialHeap< T, Predicate >::FlagTree::FlagTree (Args &&... args) inline private
Definition at line 25 of file BinomialHeap.h.
                             :
      _data(std::forward<Args>(args)...), _left(nullptr), _right(nullptr) {
    }
References _data, _left, and _right.
Referenced by FlagTree(), FlagTree(), FlagTree(), operator=(), and operator=().
FlagTree() [2/4]
template<typename T, typename Predicate> BinomialHeap< T, Predicate >::FlagTree::FlagTree (const FlagTree & rhs) inline private
Definition at line 29 of file BinomialHeap.h.
                                  :
      _data(rhs._data), _left((rhs._left ? new FlagTree(*rhs._left) : nullptr)), _right(_right = (rhs._right ? new FlagTree(*rhs._right) : nullptr)) {
    }
References _data, _left, _right, and FlagTree().
FlagTree() [3/4]
template<typename T, typename Predicate> BinomialHeap< T, Predicate >::FlagTree::FlagTree (FlagTree & rhs) inline private
Definition at line 33 of file BinomialHeap.h.
                            :
      FlagTree(const_cast<const FlagTree&>(rhs)) {
      //override perfect forwarding from variadic constructor
    }
References FlagTree().
FlagTree() [4/4]
template<typename T, typename Predicate> BinomialHeap< T, Predicate >::FlagTree::FlagTree (FlagTree && rhs) inline private noexcept
Definition at line 38 of file BinomialHeap.h.
                                      :
      _data(std::move(rhs._data)), _left(std::exchange(rhs._left, nullptr)), _right(std::exchange(rhs._right, nullptr)) {
    }
References FlagTree().
~FlagTree()
template<typename T, typename Predicate> BinomialHeap< T, Predicate >::FlagTree::~FlagTree () inline private
Definition at line 42 of file BinomialHeap.h.
                {
      delete _left;
      delete _right;
    }
References _left, and _right.
Member Function Documentation
operator=() [1/2]
template<typename T, typename Predicate> FlagTree & BinomialHeap< T, Predicate >::FlagTree::operator= (const FlagTree & rhs) private delete
References FlagTree().
operator=() [2/2]
template<typename T, typename Predicate> FlagTree & BinomialHeap< T, Predicate >::FlagTree::operator= (FlagTree && rhs) private delete
References FlagTree().
Friends And Related Symbol Documentation
BinomialHeap
template<typename T, typename Predicate> friend class BinomialHeap friend
Definition at line 50 of file BinomialHeap.h.
References BinomialHeap.
Referenced by BinomialHeap.
Member Data Documentation
_data
template<typename T, typename Predicate> T BinomialHeap< T, Predicate >::FlagTree::_data private
Definition at line 20 of file BinomialHeap.h.
Referenced by FlagTree(), FlagTree(), and BinomialHeap< T, Predicate >::MergeToHeight().
_left
template<typename T, typename Predicate> FlagTree* BinomialHeap< T, Predicate >::FlagTree::_left private
Definition at line 21 of file BinomialHeap.h.
Referenced by FlagTree(), FlagTree(), BinomialHeap< T, Predicate >::MergeToHeight(), and ~FlagTree().
_right
template<typename T, typename Predicate> FlagTree* BinomialHeap< T, Predicate >::FlagTree::_right private
Definition at line 22 of file BinomialHeap.h.
Referenced by FlagTree(), FlagTree(), BinomialHeap< T, Predicate >::Pop(), and ~FlagTree().
The documentation for this class was generated from the following file:
C:/Users/evanh/Desktop/DataStructure/DataStructure/BinomialHeap.h