Flow: AVLTree< T >::Node Class Reference
AVLTree< T >::Node Class Reference
#include <AVLTree.h>
Public Member Functions
Node (const T &key)
Node (T &&key)
Node (const Node &rhs)
Node (Node &&rhs) noexcept
~Node ()
Node & operator= (const Node &rhs)=delete
Node & operator= (Node &&rhs)=delete
T * Min ()
T * Max ()
const T * Min () const
const T * Max () const
std::string Print (const int depth, int &max_depth, int &max_breadth)
Static Public Member Functions
static T * Find (Node *curr, const T &key)
static const T * Find (const Node *curr, const T &key)
template<typename Arg>
static void Push (Node **parent, Node *curr, Arg &&key)
static void Erase (Node **parent, Node *curr, const T &key)
static void EraseReplacement (Node **parent, Node *curr, Node *root)
static void BalanceSubtree (Node **parent, Node *root)
Private Member Functions
void UpdateInfo ()
void RotateLeftLeft (Node **parent)
void RotateLeftRight (Node **parent)
void RotateRightRight (Node **parent)
void RotateRightLeft (Node **parent)
Private Attributes
short height_
short balance_factor_
T key_
Node * left_
Node * right_
Detailed Description
template<typename T>
class AVLTree< T >::Node
Definition at line 171 of file AVLTree.h.
Constructor & Destructor Documentation
Node() [1/4]
template<typename T> AVLTree< T >::Node::Node (const T & key)
Definition at line 216 of file AVLTree.h.
                                 :
  height_(0), balance_factor_(0), key_(key), left_(nullptr), right_(nullptr) {}
References balance_factor_, height_, key_, left_, and right_.
Referenced by BalanceSubtree(), Erase(), EraseReplacement(), Find(), Find(), Node(), Node(), operator=(), operator=(), Push(), RotateLeftLeft(), RotateLeftRight(), RotateRightLeft(), and RotateRightRight().
Node() [2/4]
template<typename T> AVLTree< T >::Node::Node (T && key)
Definition at line 220 of file AVLTree.h.
                            :
  height_(0), balance_factor_(0), key_(std::move(key)), left_(nullptr), right_(nullptr) {}
References balance_factor_, height_, key_, left_, and right_.
Node() [3/4]
template<typename T> AVLTree< T >::Node::Node (const Node & rhs)
Definition at line 224 of file AVLTree.h.
                                    :
  height_(rhs.height_), balance_factor_(rhs.balance_factor_), key_(rhs.key_) {
  left_ = (rhs.left_ ? new Node(*rhs.left_) : nullptr);
  right_ = (rhs.right_ ? new Node(*rhs.right_) : nullptr);
}
References balance_factor_, height_, key_, left_, Node(), and right_.
Node() [4/4]
template<typename T> AVLTree< T >::Node::Node (Node && rhs) noexcept
Definition at line 231 of file AVLTree.h.
                                        :
  height_(rhs.height_), balance_factor_(rhs.balance_factor_), key_(std::move(rhs.key_)), left_(std::exchange(rhs.left_, nullptr), right_(std::exchange(rhs.right_, nullptr))) {}
References balance_factor_, height_, key_, left_, Node(), and right_.
~Node()
template<typename T> AVLTree< T >::Node::~Node ()
Definition at line 235 of file AVLTree.h.
                      {
  delete this->left_;
  delete this->right_;
}
References left_, and right_.
Member Function Documentation
BalanceSubtree()
template<typename T> void AVLTree< T >::Node::BalanceSubtree (Node ** parent, Node * root) static
Definition at line 389 of file AVLTree.h.
{
  //update height and balance factor
  root->UpdateInfo();
  //rotate based on balanced factor
  if (root->balance_factor_ <= -2) {
    //left heavy
    assert(root->left_);
    if (root->left_->balance_factor_ <= 0) {
      root->RotateLeftLeft(parent);
    } else {
      root->RotateLeftRight(parent);
    }
  } else if (root->balance_factor_ >= 2) {
    //right heavy
    assert(root->right_);
    if (root->right_->balance_factor_ >= 0) {
      root->RotateRightRight(parent);
    } else {
      root->RotateRightLeft(parent);
    }
  }
  //check post balance factor
  assert((root->right_ ? root->right_->height_ : -1) - (root->left_ ? root->left_->height_ : -1) == root->balance_factor_);
}
References balance_factor_, height_, left_, Node(), right_, RotateLeftLeft(), RotateLeftRight(), RotateRightLeft(), RotateRightRight(), and UpdateInfo().
Referenced by Erase(), EraseReplacement(), operator=(), and Push().
Erase()
template<typename T> void AVLTree< T >::Node::Erase (Node ** parent, Node * curr, const T & key) static
Definition at line 329 of file AVLTree.h.
{
  //key does not exist
  if (!curr) {
    return;
  }
  if (key < curr->key_) {
    //check left subtree
    Erase(&curr->left_, curr->left_, key);
  } else if (curr->key_ < key) {
    //check right subtree
    Erase(&curr->right_, curr->right_, key);
  } else {
    //found the node
    if (curr->left_) {
      //max node in left subtree
      EraseReplacement(&curr->left_, curr->left_, curr);
      BalanceSubtree(parent, curr);
    } else if (curr->right_) {
      //right child only
      *parent = std::exchange(curr->right_, nullptr);
      delete curr;
    } else {
      //leaf node
      *parent = nullptr;
      delete curr;
    }
    return;
  }
  BalanceSubtree(parent, curr);
}
References BalanceSubtree(), AVLTree< T >::Erase(), EraseReplacement(), key_, left_, Node(), and right_.
Referenced by AVLTree< T >::Erase().
EraseReplacement()
template<typename T> void AVLTree< T >::Node::EraseReplacement (Node ** parent, Node * curr, Node * root) static
Definition at line 375 of file AVLTree.h.
{
  //finding the max node in the subtree
  if (curr->right_) {
    EraseReplacement(&curr->right_, curr->right_, root);
    BalanceSubtree(parent, root);
  } else {
    root->key_ = std::move(curr->key_);
    *parent = std::exchange(curr->left_, nullptr);
    delete curr;
  }
}
References BalanceSubtree(), EraseReplacement(), key_, left_, Node(), and right_.
Referenced by Erase(), EraseReplacement(), and operator=().
Find() [1/2]
template<typename T> const T * AVLTree< T >::Node::Find (const Node * curr, const T & key) static
Definition at line 286 of file AVLTree.h.
{
  if (!curr) {
    return nullptr;
  }
  if (key < curr->key_) {
    return Find(curr->left_, key);
  } else if (curr->key_ < key) {
    return Find(curr->right_, key);
  } else {
    return &curr->key_;
  }
}
References AVLTree< T >::Find(), key_, left_, Node(), and right_.
Find() [2/2]
template<typename T> T * AVLTree< T >::Node::Find (Node * curr, const T & key) static
Definition at line 301 of file AVLTree.h.
{
  return const_cast<T*>(Find(static_cast<const Node*>(curr), key));
}
References AVLTree< T >::Find(), and Node().
Referenced by AVLTree< T >::Find().
Max() [1/2]
template<typename T> T * AVLTree< T >::Node::Max ()
Definition at line 256 of file AVLTree.h.
                       {
  return const_cast<T*>(static_cast<const AVLTree<T>::Node&>(*this).Max());
}
References Max().
Referenced by Max().
Max() [2/2]
template<typename T> const T * AVLTree< T >::Node::Max () const
Definition at line 251 of file AVLTree.h.
{
  return (this->right_ ? this->right_->Max() : &this->key_);
}
References right_.
Min() [1/2]
template<typename T> T * AVLTree< T >::Node::Min ()
Definition at line 246 of file AVLTree.h.
                       {
  return const_cast<T*>(static_cast<const AVLTree<T>::Node&>(*this).Min());
}
References Min().
Referenced by Min().
Min() [2/2]
template<typename T> const T * AVLTree< T >::Node::Min () const
Definition at line 241 of file AVLTree.h.
{
  return (this->left_ ? this->left_->Min() : &this->key_);
}
References left_.
operator=() [1/2]
template<typename T> Node & AVLTree< T >::Node::operator= (const Node & rhs) delete
References Node().
operator=() [2/2]
template<typename T> Node & AVLTree< T >::Node::operator= (Node && rhs) delete
References BalanceSubtree(), EraseReplacement(), Node(), RotateLeftLeft(), RotateLeftRight(), RotateRightLeft(), RotateRightRight(), and UpdateInfo().
Print()
template<typename T> std::string AVLTree< T >::Node::Print (const int depth, int & max_depth, int & max_breadth)
Definition at line 261 of file AVLTree.h.
{
  //std::string tree_str(std::to_string(this->height_) + "(" + std::to_string(this->balance_factor_) + ")");
  std::string tree_str(std::to_string(this->key_));
  if (this->left_ || this->right_) {
    tree_str += " -> ";
  }
  const std::string space = std::string((depth + 1) * 5, ' ') + "|";
  if (this->right_) {
    tree_str += "\n" + space + this->right_->Print(depth + 1, max_depth, max_breadth);
  }
  if (this->left_) {
    tree_str += "\n" + space + this->left_->Print(depth + 1, max_depth, max_breadth);
  }
  //update the max_depth
  max_depth = std::max(max_depth, depth);
  max_breadth = std::max(max_breadth, int(this->height_));
  return tree_str;
}
References height_, key_, left_, and right_.
Push()
template<typename T> template<typename Arg> void AVLTree< T >::Node::Push (Node ** parent, Node * curr, Arg && key) static
Definition at line 307 of file AVLTree.h.
{
  //null leaf
  if (!curr) {
    (*parent) = new Node(std::forward<Arg>(key));
    return;
  }
  //check subtree
  if (key < curr->key_) {
    Push(&curr->left_, curr->left_, std::forward<Arg>(key));
  } else if (curr->key_ < key) {
    Push(&curr->right_, curr->right_, std::forward<Arg>(key));
  } else {
    return;
  }
  //balance the subtree
  BalanceSubtree(parent, curr);
}
References BalanceSubtree(), key_, left_, Node(), AVLTree< T >::Push(), and right_.
Referenced by AVLTree< T >::Push().
RotateLeftLeft()
template<typename T> void AVLTree< T >::Node::RotateLeftLeft (Node ** parent) private
Definition at line 433 of file AVLTree.h.
{
  Node* const L = this->left_;
  *parent = L;
  this->left_ = L->right_;
  L->right_ = this;
  //update height and balance factor for this node and new parent node
  //left subtree remain the same
  this->UpdateInfo();
  (*parent)->UpdateInfo();
}
References left_, Node(), right_, and UpdateInfo().
Referenced by BalanceSubtree(), and operator=().
RotateLeftRight()
template<typename T> void AVLTree< T >::Node::RotateLeftRight (Node ** parent) private
Definition at line 448 of file AVLTree.h.
{
  Node* const L = this->left_;
  Node* const LR = L->right_;
  *parent = LR;
  L->right_ = LR->left_;
  this->left_ = LR->right_;
  LR->left_ = L;
  LR->right_ = this;
  this->UpdateInfo();
  (*parent)->left_->UpdateInfo();
  (*parent)->UpdateInfo();
}
References left_, Node(), right_, and UpdateInfo().
Referenced by BalanceSubtree(), and operator=().
RotateRightLeft()
template<typename T> void AVLTree< T >::Node::RotateRightLeft (Node ** parent) private
Definition at line 478 of file AVLTree.h.
{
  Node* const R = this->right_;
  Node* const RL = R->left_;
  *parent = RL;
  R->left_ = RL->right_;
  this->right_ = RL->left_;
  RL->right_ = R;
  RL->left_ = this;
  this->UpdateInfo();
  (*parent)->right_->UpdateInfo();
  (*parent)->UpdateInfo();
}
References left_, Node(), right_, and UpdateInfo().
Referenced by BalanceSubtree(), and operator=().
RotateRightRight()
template<typename T> void AVLTree< T >::Node::RotateRightRight (Node ** parent) private
Definition at line 465 of file AVLTree.h.
{
  Node* const R = this->right_;
  *parent = R;
  this->right_ = R->left_;
  R->left_ = this;
  this->UpdateInfo();
  (*parent)->UpdateInfo();
}
References left_, Node(), right_, and UpdateInfo().
Referenced by BalanceSubtree(), and operator=().
UpdateInfo()
template<typename T> void AVLTree< T >::Node::UpdateInfo () private
Definition at line 425 of file AVLTree.h.
{
  const short left_height = (this->left_ ? this->left_->height_ : -1);
  const short right_height = (this->right_ ? this->right_->height_ : -1);
  this->height_ = std::max(left_height, right_height) + 1;
  this->balance_factor_ = right_height - left_height;
}
References balance_factor_, height_, left_, and right_.
Referenced by BalanceSubtree(), operator=(), RotateLeftLeft(), RotateLeftRight(), RotateRightLeft(), and RotateRightRight().
Member Data Documentation
balance_factor_
template<typename T> short AVLTree< T >::Node::balance_factor_ private
Definition at line 174 of file AVLTree.h.
Referenced by BalanceSubtree(), Node(), Node(), Node(), Node(), and UpdateInfo().
height_
template<typename T> short AVLTree< T >::Node::height_ private
Definition at line 173 of file AVLTree.h.
Referenced by BalanceSubtree(), Node(), Node(), Node(), Node(), Print(), and UpdateInfo().
key_
template<typename T> T AVLTree< T >::Node::key_ private
Definition at line 175 of file AVLTree.h.
Referenced by Erase(), EraseReplacement(), Find(), Node(), Node(), Node(), Node(), Print(), and Push().
left_
template<typename T> Node* AVLTree< T >::Node::left_ private
Definition at line 176 of file AVLTree.h.
Referenced by BalanceSubtree(), Erase(), EraseReplacement(), Find(), Min(), Node(), Node(), Node(), Node(), Print(), Push(), RotateLeftLeft(), RotateLeftRight(), RotateRightLeft(), RotateRightRight(), UpdateInfo(), and ~Node().
right_
template<typename T> Node* AVLTree< T >::Node::right_ private
Definition at line 177 of file AVLTree.h.
Referenced by BalanceSubtree(), Erase(), EraseReplacement(), Find(), Max(), Node(), Node(), Node(), Node(), Print(), Push(), RotateLeftLeft(), RotateLeftRight(), RotateRightLeft(), RotateRightRight(), UpdateInfo(), and ~Node().
The documentation for this class was generated from the following file:
AVLTree.h