Flow: SkipList< KeyType, ValueType, Predicate > Class Template Reference
SkipList< KeyType, ValueType, Predicate > Class Template Reference
#include <SkipList.h>
Classes
class IteratorImpl
struct Node
struct Tower
Public Types
using Iterator = IteratorImpl<KeyValueType&>
using ConstIterator = IteratorImpl<const KeyValueType&>
Public Member Functions
Iterator begin ()
ConstIterator begin () const
Iterator end ()
ConstIterator end () const
Iterator Find (const KeyType &key)
ConstIterator Find (const KeyType &key) const
void Insert (const KeyValueType &keyValue)
void Erase (const KeyType &key)
void Print () const
SkipList ()
SkipList (const SkipList &other)=delete
SkipList (SkipList &&other) noexcept
~SkipList ()
SkipList & operator= (const SkipList &other)=delete
SkipList & operator= (SkipList &&other) noexcept
Private Types
using KeyValueType = std::pair<const KeyType, ValueType>
Private Member Functions
std::vector< Node * > GetPredecessors (const KeyType &key) const
Private Attributes
Tower * _root
Static Private Attributes
static const Predicate comp {}
Detailed Description
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>>
class SkipList< KeyType, ValueType, Predicate >
Definition at line 10 of file SkipList.h.
Member Typedef Documentation
ConstIterator
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> using SkipList< KeyType, ValueType, Predicate >::ConstIterator = IteratorImpl<const KeyValueType&>
Definition at line 97 of file SkipList.h.
Iterator
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> using SkipList< KeyType, ValueType, Predicate >::Iterator = IteratorImpl<KeyValueType&>
Definition at line 96 of file SkipList.h.
KeyValueType
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> using SkipList< KeyType, ValueType, Predicate >::KeyValueType = std::pair<const KeyType, ValueType> private
Definition at line 11 of file SkipList.h.
Constructor & Destructor Documentation
SkipList() [1/3]
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> SkipList< KeyType, ValueType, Predicate >::SkipList () inline explicit
Definition at line 177 of file SkipList.h.
: _root(new Tower()) {}
References _root.
Referenced by operator=(), operator=(), SkipList(), and SkipList().
SkipList() [2/3]
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> SkipList< KeyType, ValueType, Predicate >::SkipList (const SkipList< KeyType, ValueType, Predicate > & other) explicit delete
References SkipList().
SkipList() [3/3]
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> SkipList< KeyType, ValueType, Predicate >::SkipList (SkipList< KeyType, ValueType, Predicate > && other) inline explicit noexcept
Definition at line 181 of file SkipList.h.
: _root(std::exchange(other._root, nullptr)) {}
References SkipList().
~SkipList()
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> SkipList< KeyType, ValueType, Predicate >::~SkipList () inline
Definition at line 183 of file SkipList.h.
              {
    for (Tower* curr = _root; curr; ) {
      Tower* next = curr->_nodes.front()._next;
      delete curr;
      curr = next;
    }
  }
References SkipList< KeyType, ValueType, Predicate >::Tower::_nodes, and _root.
Member Function Documentation
begin() [1/2]
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> Iterator SkipList< KeyType, ValueType, Predicate >::begin () inline
Definition at line 99 of file SkipList.h.
                   {
    return Iterator(_root->_nodes.front()->_next);
  }
References _root.
begin() [2/2]
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> ConstIterator SkipList< KeyType, ValueType, Predicate >::begin () const inline
Definition at line 103 of file SkipList.h.
{
    return ConstIterator(_root->_nodes.front()->_next);
  }
References _root.
end() [1/2]
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> Iterator SkipList< KeyType, ValueType, Predicate >::end () inline
Definition at line 107 of file SkipList.h.
                 {
    return Iterator(nullptr);
  }
Referenced by Insert().
end() [2/2]
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> ConstIterator SkipList< KeyType, ValueType, Predicate >::end () const inline
Definition at line 111 of file SkipList.h.
{
    return ConstIterator(nullptr);
  }
Erase()
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> void SkipList< KeyType, ValueType, Predicate >::Erase (const KeyType & key) inline
Definition at line 145 of file SkipList.h.
{
    auto predecessors = GetPredecessors(key);
    Tower* const tower = predecessors.back()->_next;
    bool found = false;
    int height = 0;
    for (auto iter = predecessors.rbegin(); iter != predecessors.rend(); ++iter, ++height) {
      Tower* const candidate = (*iter)->_next;
      if (candidate && !comp(candidate->Key(), key) && !comp(key, candidate->Key())) {
        (*iter)->_next = candidate->_nodes[height]._next;
        found = true;
      } else {
        break;
      }
    }
    if (found) {
      delete tower;
    }
  }
References SkipList< KeyType, ValueType, Predicate >::Tower::_nodes, comp, GetPredecessors(), and SkipList< KeyType, ValueType, Predicate >::Tower::Key().
Find() [1/2]
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> Iterator SkipList< KeyType, ValueType, Predicate >::Find (const KeyType & key) inline
Definition at line 115 of file SkipList.h.
{
    Tower* const tower = GetPredecessors(key).back()->_next;
    return Iterator((tower && !comp(tower->Key(), key) && !comp(key, tower->Key())) ? tower : nullptr); //is == defined?, should I use < instead?
  }
References comp, GetPredecessors(), and SkipList< KeyType, ValueType, Predicate >::Tower::Key().
Referenced by Insert().
Find() [2/2]
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> ConstIterator SkipList< KeyType, ValueType, Predicate >::Find (const KeyType & key) const inline
Definition at line 120 of file SkipList.h.
{
    Tower* const tower = GetPredecessors(key).back()->_next;
    return ConstIterator((tower && !comp(tower->Key(), key) && !comp(key, tower->Key())) ? tower : nullptr);
  }
References comp, GetPredecessors(), and SkipList< KeyType, ValueType, Predicate >::Tower::Key().
GetPredecessors()
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> std::vector< Node * > SkipList< KeyType, ValueType, Predicate >::GetPredecessors (const KeyType & key) const inline private
Definition at line 76 of file SkipList.h.
{
    Tower* currTower = _root;
    int height = int(_root->_nodes.size()) - 1;
    std::vector<Node*> predecessors = { &currTower->_nodes[height] };
    //go down by 1 height each iteration
    while (--height >= 0) {
      //search horizontally until reaches the upper bound or sentinel
      Node* currNode = &currTower->_nodes[height];
      while (currNode->_next && comp(currNode->_next->Key(), key)) {
        currNode = &currNode->_next->_nodes[height];
      }
      predecessors.push_back(currNode);
    }
    return predecessors;
  }
References SkipList< KeyType, ValueType, Predicate >::Node::_next, SkipList< KeyType, ValueType, Predicate >::Tower::_nodes, _root, comp, and SkipList< KeyType, ValueType, Predicate >::Tower::Key().
Referenced by Erase(), Find(), Find(), and Insert().
Insert()
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> void SkipList< KeyType, ValueType, Predicate >::Insert (const KeyValueType & keyValue) inline
Definition at line 125 of file SkipList.h.
{
    if (auto result = Find(keyValue.first); result != end()) {
      (*result).second = keyValue.second;
      return;
    }
    //insert the new tower
    Tower* newTower = new Tower(keyValue); //pray it doesn't throw, this strategy always works
    if (_root->_nodes.size() <= newTower->_nodes.size()) {
      _root->_nodes.resize(newTower->_nodes.size() + 1);
    }
    auto predecessors = GetPredecessors(keyValue.first);
    for (Node& node : newTower->_nodes) {
      node._next = predecessors.back()->_next;
      predecessors.back()->_next = newTower;
      predecessors.pop_back();
    }
  }
References SkipList< KeyType, ValueType, Predicate >::Node::_next, SkipList< KeyType, ValueType, Predicate >::Tower::_nodes, _root, end(), Find(), and GetPredecessors().
operator=() [1/2]
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> SkipList & SkipList< KeyType, ValueType, Predicate >::operator= (const SkipList< KeyType, ValueType, Predicate > & other) delete
References SkipList().
operator=() [2/2]
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> SkipList & SkipList< KeyType, ValueType, Predicate >::operator= (SkipList< KeyType, ValueType, Predicate > && other) inline noexcept
Definition at line 193 of file SkipList.h.
{
    std::swap(_root, other._root);
  }
References _root, and SkipList().
Print()
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> void SkipList< KeyType, ValueType, Predicate >::Print () const inline
Definition at line 166 of file SkipList.h.
                     {
    for (int i = int(_root->_nodes.size()) - 1; i >= 0; --i) {
      Node node = _root->_nodes[i];
      for (Tower* tower = node._next; tower; ) {
        std::cout << "_(" << tower->Key() << ", " << tower->Value() << ")";
        tower = tower->_nodes[i]._next;
      }
      std::cout << '\n';
    }
  }
References SkipList< KeyType, ValueType, Predicate >::Node::_next, and _root.
Member Data Documentation
_root
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> Tower* SkipList< KeyType, ValueType, Predicate >::_root private
Definition at line 74 of file SkipList.h.
Referenced by begin(), begin(), GetPredecessors(), Insert(), operator=(), Print(), SkipList(), and ~SkipList().
comp
template<typename KeyType, typename ValueType, typename Predicate = std::less<KeyType>> const Predicate SkipList< KeyType, ValueType, Predicate >::comp {} inline static private
Definition at line 13 of file SkipList.h.
{};
Referenced by Erase(), Find(), Find(), and GetPredecessors().
The documentation for this class was generated from the following file:
C:/Users/evanh/Desktop/DataStructure/DataStructure/SkipList.h