Flow: IntegerIterator< T > Class Template Reference
IntegerIterator< T > Class Template Reference
#include <IntegerIterator.h>
Public Types
using value_type = T
using difference_type = std::ptrdiff_t
using reference = T
using pointer = T*
using iterator_category = std::random_access_iterator_tag
Public Member Functions
IntegerIterator (const T &value)
reference operator* () const
pointer operator-> () const
IntegerIterator & operator++ ()
IntegerIterator operator++ (int)
IntegerIterator & operator-- ()
IntegerIterator operator-- (int)
IntegerIterator & operator+= (difference_type n)
difference_type operator- (IntegerIterator &rhs) const
reference operator[] (difference_type n) const
Private Attributes
T _value
Friends
bool operator< (const IntegerIterator &lhs, const IntegerIterator &rhs)
bool operator== (const IntegerIterator &lhs, const IntegerIterator &rhs)
void swap (IntegerIterator &lhs, IntegerIterator &rhs)
Detailed Description
template<typename T>
class IntegerIterator< T >
Definition at line 7 of file IntegerIterator.h.
Member Typedef Documentation
difference_type
template<typename T> using IntegerIterator< T >::difference_type = std::ptrdiff_t
Definition at line 12 of file IntegerIterator.h.
iterator_category
template<typename T> using IntegerIterator< T >::iterator_category = std::random_access_iterator_tag
Definition at line 15 of file IntegerIterator.h.
pointer
template<typename T> using IntegerIterator< T >::pointer = T*
Definition at line 14 of file IntegerIterator.h.
reference
template<typename T> using IntegerIterator< T >::reference = T
Definition at line 13 of file IntegerIterator.h.
value_type
template<typename T> using IntegerIterator< T >::value_type = T
Definition at line 11 of file IntegerIterator.h.
Constructor & Destructor Documentation
IntegerIterator()
template<typename T> IntegerIterator< T >::IntegerIterator (const T & value) inline
Definition at line 17 of file IntegerIterator.h.
                                  : _value(value) {
    using Trait = typename std::iterator_traits<IntegerIterator>::iterator_category;
    static_assert(std::is_convertible_v<Trait, std::bidirectional_iterator_tag>, "not bidirectional iterator");
    static_assert(std::is_convertible_v<Trait, std::random_access_iterator_tag>, "not random access iterator");
    static_assert(std::is_integral_v<T>, "IntegerIterator only supports integer type");
  }
References _value.
Referenced by operator++(), operator++(), operator+=(), operator-(), operator--(), operator--(), operator<, operator==, and swap.
Member Function Documentation
operator*()
template<typename T> reference IntegerIterator< T >::operator* () const inline
Definition at line 24 of file IntegerIterator.h.
{ return _value; }
References _value.
operator++() [1/2]
template<typename T> IntegerIterator & IntegerIterator< T >::operator++ () inline
Definition at line 27 of file IntegerIterator.h.
{
    ++_value;
    return *this;
  }
References _value, and IntegerIterator().
operator++() [2/2]
template<typename T> IntegerIterator IntegerIterator< T >::operator++ (int) inline
Definition at line 32 of file IntegerIterator.h.
{
    IntegerIterator it = *this;
    ++*this;
    return it;
  }
References IntegerIterator().
operator+=()
template<typename T> IntegerIterator & IntegerIterator< T >::operator+= (difference_type n) inline
Definition at line 49 of file IntegerIterator.h.
{
    _value += n;
    return *this;
  }
References _value, and IntegerIterator().
operator-()
template<typename T> difference_type IntegerIterator< T >::operator- (IntegerIterator< T > & rhs) const inline
Definition at line 54 of file IntegerIterator.h.
{
    return _value - rhs._value;
  }
References _value, and IntegerIterator().
operator--() [1/2]
template<typename T> IntegerIterator & IntegerIterator< T >::operator-- () inline
Definition at line 38 of file IntegerIterator.h.
{
    --_value;
    return *this;
  }
References _value, and IntegerIterator().
operator--() [2/2]
template<typename T> IntegerIterator IntegerIterator< T >::operator-- (int) inline
Definition at line 43 of file IntegerIterator.h.
{
    IntegerIterator it = *this;
    --*this;
    return it;
  }
References IntegerIterator().
operator->()
template<typename T> pointer IntegerIterator< T >::operator-> () const inline
Definition at line 25 of file IntegerIterator.h.
{ return &_value; }
References _value.
operator[]()
template<typename T> reference IntegerIterator< T >::operator[] (difference_type n) const inline
Definition at line 58 of file IntegerIterator.h.
{
    return _value + n;
  }
References _value.
Friends And Related Symbol Documentation
operator<
template<typename T> bool operator< (const IntegerIterator< T > & lhs, const IntegerIterator< T > & rhs) friend
Definition at line 62 of file IntegerIterator.h.
{
    return lhs._value < rhs._value;
  }
References _value, and IntegerIterator().
operator==
template<typename T> bool operator== (const IntegerIterator< T > & lhs, const IntegerIterator< T > & rhs) friend
Definition at line 66 of file IntegerIterator.h.
{
    return lhs._value == rhs._value;
  }
References _value, and IntegerIterator().
swap
template<typename T> void swap (IntegerIterator< T > & lhs, IntegerIterator< T > & rhs) friend
Definition at line 70 of file IntegerIterator.h.
{
    using std::swap;
    swap(lhs._value, rhs._value);
  }
References _value, IntegerIterator(), and swap.
Referenced by swap.
Member Data Documentation
_value
template<typename T> T IntegerIterator< T >::_value private
Definition at line 8 of file IntegerIterator.h.
Referenced by IntegerIterator(), operator*(), operator++(), operator+=(), operator-(), operator--(), operator->(), operator<, operator==, operator[](), and swap.
The documentation for this class was generated from the following file:
IntegerIterator.h