Flow: SparseTable< T, BinOp > Class Template Reference
SparseTable< T, BinOp > Class Template Reference
#include <SparseTable.h>
Public Member Functions
SparseTable (std::vector< T > arr, BinOp op=BinOp())
T Query (int left, int right, BinOp op=BinOp()) const
T FastQuery (int left, int right, BinOp op=BinOp()) const
void Print (int width) const
Static Public Member Functions
static int Pow2 (int power)
Private Attributes
std::vector< std::vector< T > > _data
Detailed Description
template<typename T, typename BinOp>
class SparseTable< T, BinOp >
Definition at line 9 of file SparseTable.h.
Constructor & Destructor Documentation
SparseTable()
template<typename T, typename BinOp> SparseTable< T, BinOp >::SparseTable (std::vector< T > arr, BinOp op = BinOp())
Definition at line 24 of file SparseTable.h.
{
    //base layer
    _data.push_back(std::move(arr));
    //increase height if the interval covering length <= arr size
    for (int h = 1; Pow2(h) <= _data[0].size(); ++h)
    {
        //allocate table length with estimated size
        int inter_len = Pow2(h - 1);
        _data.push_back(std::vector<T>(_data[h - 1].size() - inter_len));
        for (int r = 0; r < _data[h].size(); ++r)
        {
            _data[h][r] = op(_data[h - 1][r], _data[h - 1][r + inter_len]);
        }
    }
}
References _data, and Pow2().
Member Function Documentation
FastQuery()
template<typename T, typename BinOp> T SparseTable< T, BinOp >::FastQuery (int left, int right, BinOp op = BinOp()) const
Definition at line 73 of file SparseTable.h.
{
}
Pow2()
template<typename T, typename BinOp> int SparseTable< T, BinOp >::Pow2 (int power) static
Definition at line 94 of file SparseTable.h.
{
    return 1 << power;
}
Referenced by Query(), and SparseTable().
Print()
template<typename T, typename BinOp> void SparseTable< T, BinOp >::Print (int width) const
Definition at line 79 of file SparseTable.h.
{
    for (const auto& row : _data)
    {
        for (const auto& column : row)
        {
            std::cout << std::setw(width) << column;
        }
        std::cout << '\n';
    }
}
References _data.
Query()
template<typename T, typename BinOp> T SparseTable< T, BinOp >::Query (int left, int right, BinOp op = BinOp()) const
Definition at line 43 of file SparseTable.h.
{
    //initial query result
    T res = _data[0][left];
    //top down
    for (int h = static_cast<int>(_data.size()) - 1; h >= 0; --h)
    {
        //check if the table includes the left index
        if (left < _data[h].size())
        {
            int inter_len = Pow2(h);
            int require_len = right - left + 1;
            //if the interval fits within the range
            if (inter_len <= require_len)
            {
                //query
                res = op(res, _data[h][left]);
                //update range
                left += inter_len;
            }
        }
    }
    return res;
}
References _data, and Pow2().
Member Data Documentation
_data
template<typename T, typename BinOp> std::vector<std::vector<T> > SparseTable< T, BinOp >::_data private
Definition at line 11 of file SparseTable.h.
Referenced by Print(), Query(), and SparseTable().
The documentation for this class was generated from the following file:
SparseTable.h