Flow: LinkedList< T > Class Template Reference
LinkedList< T > Class Template Reference
#include <LinkedList.h>
Classes
class IteratorImpl
class Node
Public Types
using Iterator = IteratorImpl<T&>
using ConstIterator = IteratorImpl<const T&>
Public Member Functions
LinkedList ()
LinkedList (const LinkedList &rhs)
LinkedList (LinkedList &&rhs) noexcept
~LinkedList ()
LinkedList & operator= (LinkedList rhs)
template<typename ... Args>
void PushFront (Args &&... args)
template<typename... Args>
void PushBack (Args &&... args)
void PopFront ()
Iterator begin ()
Iterator end ()
ConstIterator begin () const
ConstIterator end () const
std::size_t size () const
Private Attributes
Node * _front
Node * _back
std::size_t _size
Friends
void swap (LinkedList &lhs, LinkedList &rhs)
Detailed Description
template<typename T>
class LinkedList< T >
Definition at line 12 of file LinkedList.h.
Member Typedef Documentation
ConstIterator
template<typename T> using LinkedList< T >::ConstIterator = IteratorImpl<const T&>
Definition at line 63 of file LinkedList.h.
Iterator
template<typename T> using LinkedList< T >::Iterator = IteratorImpl<T&>
Definition at line 62 of file LinkedList.h.
Constructor & Destructor Documentation
LinkedList() [1/3]
template<typename T> LinkedList< T >::LinkedList () inline
Definition at line 65 of file LinkedList.h.
: _front(), _back(), _size(0) {};
References _back, _front, and _size.
Referenced by LinkedList(), LinkedList(), operator=(), and swap.
LinkedList() [2/3]
template<typename T> LinkedList< T >::LinkedList (const LinkedList< T > & rhs) inline
Definition at line 67 of file LinkedList.h.
                                    :
    LinkedList() {
    for (const T& data : rhs) {
      PushBack(data);
    }
  }
References LinkedList(), and PushBack().
LinkedList() [3/3]
template<typename T> LinkedList< T >::LinkedList (LinkedList< T > && rhs) inline noexcept
Definition at line 74 of file LinkedList.h.
                                        :
    _front(std::exchange(rhs._front, nullptr)),
    _back(std::exchange(rhs._back, nullptr)),
    _size(std::exchange(rhs._size, 0)) {
  }
References LinkedList().
~LinkedList()
template<typename T> LinkedList< T >::~LinkedList () inline
Definition at line 80 of file LinkedList.h.
                {
    while (_front) {
      Node* next = _front->_next;
      delete _front;
      _front = next;
    }
  }
References _front.
Member Function Documentation
begin() [1/2]
template<typename T> Iterator LinkedList< T >::begin () inline
Definition at line 128 of file LinkedList.h.
{ return Iterator(_front); }
References _front.
begin() [2/2]
template<typename T> ConstIterator LinkedList< T >::begin () const inline
Definition at line 130 of file LinkedList.h.
{ return ConstIterator(_front); }
References _front.
end() [1/2]
template<typename T> Iterator LinkedList< T >::end () inline
Definition at line 129 of file LinkedList.h.
{ return Iterator(nullptr); }
end() [2/2]
template<typename T> ConstIterator LinkedList< T >::end () const inline
Definition at line 131 of file LinkedList.h.
{ return ConstIterator(nullptr); }
operator=()
template<typename T> LinkedList & LinkedList< T >::operator= (LinkedList< T > rhs) inline
Definition at line 88 of file LinkedList.h.
{
    swap(*this, rhs);
    return *this;
  }
References LinkedList(), and swap.
PopFront()
template<typename T> void LinkedList< T >::PopFront () inline
Definition at line 118 of file LinkedList.h.
                  {
    assert(_size > 0 && "pop front from an empty list");
    Node* old = _front;
    _front = _front->_next;
    if (--_size == 0) {
      _back = nullptr;
    }
    delete old;
  }
References _back, _front, and _size.
PushBack()
template<typename T> template<typename... Args> void LinkedList< T >::PushBack (Args &&... args) inline
Definition at line 106 of file LinkedList.h.
{
    Node* node = new Node(std::forward<Args>(args)...);
    if (_size == 0) {
      assert(!_front);
      _front = node;
    } else {
      _back->_next = node;
    }
    _back = node;
    ++_size;
  }
References _back, _front, and _size.
Referenced by LinkedList().
PushFront()
template<typename T> template<typename ... Args> void LinkedList< T >::PushFront (Args &&... args) inline
Definition at line 94 of file LinkedList.h.
{
    Node* node = new Node(std::forward<Args>(args)...);
    node->_next = _front;
    _front = node;
    if (_size == 0) {
      assert(!_back);
      _back = _front;
    }
    ++_size;
  }
References _back, _front, LinkedList< T >::Node::_next, and _size.
size()
template<typename T> std::size_t LinkedList< T >::size () const inline
Definition at line 132 of file LinkedList.h.
{ return _size; }
References _size.
Friends And Related Symbol Documentation
swap
template<typename T> void swap (LinkedList< T > & lhs, LinkedList< T > & rhs) friend
Definition at line 138 of file LinkedList.h.
{
  using std::swap;
  swap(lhs._front, rhs._front);
  swap(lhs._back, rhs._back);
  swap(lhs._size, rhs._size);
}
References _back, _front, _size, LinkedList(), and swap().
Referenced by operator=().
Member Data Documentation
_back
template<typename T> Node* LinkedList< T >::_back private
Definition at line 58 of file LinkedList.h.
Referenced by LinkedList(), PopFront(), PushBack(), PushFront(), and swap.
_front
template<typename T> Node* LinkedList< T >::_front private
Definition at line 57 of file LinkedList.h.
Referenced by begin(), begin(), LinkedList(), PopFront(), PushBack(), PushFront(), swap, and ~LinkedList().
_size
template<typename T> std::size_t LinkedList< T >::_size private
Definition at line 59 of file LinkedList.h.
Referenced by LinkedList(), PopFront(), PushBack(), PushFront(), size(), and swap.
The documentation for this class was generated from the following file:
LinkedList.h