Flow: BinaryHeap< T, Predicate > Class Template Reference
BinaryHeap< T, Predicate > Class Template Reference
#include <BinaryHeap.h>
Public Member Functions
BinaryHeap ()=default
BinaryHeap (std::vector< T > arr)
template<typename ... Args>
void Push (Args &&... args)
void Pop ()
const T & Top () const
std::size_t Size () const
Private Member Functions
int Parent (int n) const
int LeftChild (int n) const
int RightChild (int n) const
void FixUp (int n, Predicate p=Predicate())
void FixDown (int n, Predicate p=Predicate())
Private Attributes
std::vector< T > _data
Detailed Description
template<typename T, typename Predicate = std::greater<T>>
class BinaryHeap< T, Predicate >
Definition at line 5 of file BinaryHeap.h.
Constructor & Destructor Documentation
BinaryHeap() [1/2]
template<typename T, typename Predicate = std::greater<T>> BinaryHeap< T, Predicate >::BinaryHeap () default
BinaryHeap() [2/2]
template<typename T, typename Predicate = std::greater<T>> BinaryHeap< T, Predicate >::BinaryHeap (std::vector< T > arr) inline
Definition at line 11 of file BinaryHeap.h.
                               : _data(std::move(arr)) {
    for (int r = Parent(_data.size() - 1); r >= 0; --r) {
      FixDown(r);
    }
  }
References _data, and Parent().
Member Function Documentation
FixDown()
template<typename T, typename Predicate = std::greater<T>> void BinaryHeap< T, Predicate >::FixDown (int n, Predicate p = Predicate()) inline private
Definition at line 55 of file BinaryHeap.h.
{
     while (true) {
      int child = LeftChild(n);
      if (child >= _data.size()) {
        break;
      }
      if (int rightChild = RightChild(n);
          rightChild < _data.size() && p(_data[rightChild], _data[child])) {
        child = rightChild;
      }
      if (p(_data[child], _data[n])) {
        std::swap(_data[n], _data[child]);
        n = child;
      } else {
        break;
      }
     }
   }
References _data, LeftChild(), and RightChild().
Referenced by Pop().
FixUp()
template<typename T, typename Predicate = std::greater<T>> void BinaryHeap< T, Predicate >::FixUp (int n, Predicate p = Predicate()) inline private
Definition at line 43 of file BinaryHeap.h.
{
     while (n > 0) {
      int parent = Parent(n);
      if (p(_data[n], _data[parent])) {
        std::swap(_data[n], _data[parent]);
        n = parent;
      } else {
        break;
      }
     }
   }
References _data, and Parent().
Referenced by Push().
LeftChild()
template<typename T, typename Predicate = std::greater<T>> int BinaryHeap< T, Predicate >::LeftChild (int n) const inline private
Definition at line 40 of file BinaryHeap.h.
{ return n * 2 + 1; }
Referenced by FixDown().
Parent()
template<typename T, typename Predicate = std::greater<T>> int BinaryHeap< T, Predicate >::Parent (int n) const inline private
Definition at line 39 of file BinaryHeap.h.
{ return (n - 1) / 2; }
Referenced by BinaryHeap(), and FixUp().
Pop()
template<typename T, typename Predicate = std::greater<T>> void BinaryHeap< T, Predicate >::Pop () inline
Definition at line 23 of file BinaryHeap.h.
             {
    _data.front() = std::move(_data.back());
    _data.pop_back();
    FixDown(0);
  }
References _data, and FixDown().
Push()
template<typename T, typename Predicate = std::greater<T>> template<typename ... Args> void BinaryHeap< T, Predicate >::Push (Args &&... args) inline
Definition at line 18 of file BinaryHeap.h.
{
    _data.emplace_back(std::forward<Args>(args)...);
    FixUp(_data.size() - 1);
  }
References _data, and FixUp().
RightChild()
template<typename T, typename Predicate = std::greater<T>> int BinaryHeap< T, Predicate >::RightChild (int n) const inline private
Definition at line 41 of file BinaryHeap.h.
{ return n * 2 + 2; }
Referenced by FixDown().
Size()
template<typename T, typename Predicate = std::greater<T>> std::size_t BinaryHeap< T, Predicate >::Size () const inline
Definition at line 34 of file BinaryHeap.h.
{
    return _data.size();
  }
References _data.
Top()
template<typename T, typename Predicate = std::greater<T>> const T & BinaryHeap< T, Predicate >::Top () const inline
Definition at line 29 of file BinaryHeap.h.
                       {
    assert(!_data.empty() && "access empty heap top");
    return _data[0];
  }
References _data.
Member Data Documentation
_data
template<typename T, typename Predicate = std::greater<T>> std::vector<T> BinaryHeap< T, Predicate >::_data private
Definition at line 6 of file BinaryHeap.h.
Referenced by BinaryHeap(), FixDown(), FixUp(), Pop(), Push(), Size(), and Top().
The documentation for this class was generated from the following file:
BinaryHeap.h