Flow: flow::CountedValueViewIterator< T > Class Template Reference
flow::CountedValueViewIterator< T > Class Template Reference
Iterator that returns a constant value for a fixed number of times. Useful for creating a virtual range of repeated values without storage.
#include <flow_counted_value_view_iterator.h>
Public Types
using value_type = T
using reference = const T&
using pointer = const T*
using difference_type = std::ptrdiff_t
using iterator_category = std::forward_iterator_tag
Public Member Functions
CountedValueViewIterator ()
CountedValueViewIterator (const T &value, std::size_t count=0)
const T & operator* () const
const T * operator-> () const
CountedValueViewIterator & operator++ ()
CountedValueViewIterator operator++ (int)
Private Attributes
const T * value_
std::size_t count_
Friends
bool operator== (const CountedValueViewIterator &lhs, const CountedValueViewIterator &rhs)
bool operator!= (const CountedValueViewIterator &lhs, const CountedValueViewIterator &rhs)
Detailed Description
template<typename T>
class flow::CountedValueViewIterator< T >
Iterator that returns a constant value for a fixed number of times. Useful for creating a virtual range of repeated values without storage.
Definition at line 13 of file flow_counted_value_view_iterator.h.
Member Typedef Documentation
difference_type
template<typename T> using flow::CountedValueViewIterator< T >::difference_type = std::ptrdiff_t
Definition at line 21 of file flow_counted_value_view_iterator.h.
iterator_category
template<typename T> using flow::CountedValueViewIterator< T >::iterator_category = std::forward_iterator_tag
Definition at line 22 of file flow_counted_value_view_iterator.h.
pointer
template<typename T> using flow::CountedValueViewIterator< T >::pointer = const T*
Definition at line 20 of file flow_counted_value_view_iterator.h.
reference
template<typename T> using flow::CountedValueViewIterator< T >::reference = const T&
Definition at line 19 of file flow_counted_value_view_iterator.h.
value_type
template<typename T> using flow::CountedValueViewIterator< T >::value_type = T
Definition at line 18 of file flow_counted_value_view_iterator.h.
Constructor & Destructor Documentation
CountedValueViewIterator() [1/2]
template<typename T> flow::CountedValueViewIterator< T >::CountedValueViewIterator () inline
Definition at line 24 of file flow_counted_value_view_iterator.h.
                               :
      value_(nullptr), count_(0) {
    }
References count_, and value_.
Referenced by operator!=, operator++(), operator++(), and operator==.
CountedValueViewIterator() [2/2]
template<typename T> flow::CountedValueViewIterator< T >::CountedValueViewIterator (const T & value, std::size_t count = 0) inline
Definition at line 28 of file flow_counted_value_view_iterator.h.
                                                                  :
      value_(&value), count_(count) {
    }
References count_, and value_.
Member Function Documentation
operator*()
template<typename T> const T & flow::CountedValueViewIterator< T >::operator* () const inline
Definition at line 32 of file flow_counted_value_view_iterator.h.
{
      assert(value_ && "no value");
      return *value_;
    }
References value_.
operator++() [1/2]
template<typename T> CountedValueViewIterator & flow::CountedValueViewIterator< T >::operator++ () inline
Definition at line 42 of file flow_counted_value_view_iterator.h.
{
      assert(count_ > 0 && "negative count");
      --count_;
      return *this;
    }
References count_, and CountedValueViewIterator().
operator++() [2/2]
template<typename T> CountedValueViewIterator flow::CountedValueViewIterator< T >::operator++ (int) inline
Definition at line 48 of file flow_counted_value_view_iterator.h.
{
      CountedValueViewIterator cpy = *this;
      --count_;
      return cpy;
    }
References count_, and CountedValueViewIterator().
operator->()
template<typename T> const T * flow::CountedValueViewIterator< T >::operator-> () const inline
Definition at line 37 of file flow_counted_value_view_iterator.h.
{
      assert(value_ && "no value");
      return value_;
    }
References value_.
Friends And Related Symbol Documentation
operator!=
template<typename T> bool operator!= (const CountedValueViewIterator< T > & lhs, const CountedValueViewIterator< T > & rhs) friend
Definition at line 58 of file flow_counted_value_view_iterator.h.
{
      return !(lhs == rhs);
    }
References CountedValueViewIterator().
operator==
template<typename T> bool operator== (const CountedValueViewIterator< T > & lhs, const CountedValueViewIterator< T > & rhs) friend
Definition at line 54 of file flow_counted_value_view_iterator.h.
{
      return lhs.count_ == rhs.count_ && lhs.value_ == rhs.value_;
    }
References count_, CountedValueViewIterator(), and value_.
Member Data Documentation
count_
template<typename T> std::size_t flow::CountedValueViewIterator< T >::count_ private
Definition at line 15 of file flow_counted_value_view_iterator.h.
Referenced by CountedValueViewIterator(), CountedValueViewIterator(), operator++(), operator++(), and operator==.
value_
template<typename T> const T* flow::CountedValueViewIterator< T >::value_ private
Definition at line 14 of file flow_counted_value_view_iterator.h.
Referenced by CountedValueViewIterator(), CountedValueViewIterator(), operator*(), operator->(), and operator==.
The documentation for this class was generated from the following file:
C:/Users/evanh/Desktop/DataStructure/DataStructure/flow_counted_value_view_iterator.h