Flow: benchmark Namespace Reference
benchmark Namespace Reference
Functions
void benchmarkStdVector (std::size_t elementSize, std::size_t benchTime)
void benchmarkFlowVector (std::size_t elementSize, std::size_t benchTime)
void benchmarkStdVectorString (std::size_t elementSize, std::size_t benchTime)
void benchmarkFlowVectorString (std::size_t elementSize, std::size_t benchTime)
void benchmarkStdSet (std::size_t elementSize, std::size_t benchTime)
Function Documentation
benchmarkFlowVector()
void benchmark::benchmarkFlowVector (std::size_t elementSize, std::size_t benchTime) inline
Definition at line 82 of file benchmark.h.
{
    using namespace std;
    using namespace flow;
    unique_ptr<int64_t[]> buffer = make_unique<int64_t[]>(elementSize * 32);
    cout << "flow::Vector raw\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      Vector<int64_t> vec{};
      Timer timer{};
      timer.reset();
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.pushBack(i);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "flow::Vector reserve\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      Vector<int64_t> vec{};
      Timer timer{};
      timer.reset();
      vec.reserve(elementSize);
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.pushBack(i);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "flow::Vector raw arena\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      ArenaMemoryResource resource(buffer.get(), elementSize * 32 * sizeof(int64_t));
      PolymorphicAllocator<> alloc{ resource };
      Vector<int64_t> vec{ alloc };
      Timer timer{};
      timer.reset();
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.pushBack(i);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "flow::Vector reserve arena\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      ArenaMemoryResource resource(buffer.get(), elementSize * 32 * sizeof(int64_t));
      PolymorphicAllocator<> alloc{ resource };
      Vector<int64_t> vec{ alloc };
      Timer timer{};
      timer.reset();
      vec.reserve(elementSize);
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.pushBack(i);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
  }
References flow::Vector< T, Allocator, Strategy >::pushBack(), flow::Timer< ClockType >::record(), flow::Vector< T, Allocator, Strategy >::reserve(), flow::Timer< ClockType >::reset(), and flow::Timer< ClockType >::toString().
benchmarkFlowVectorString()
void benchmark::benchmarkFlowVectorString (std::size_t elementSize, std::size_t benchTime) inline
Definition at line 214 of file benchmark.h.
{
    using namespace std;
    using namespace flow;
    const string sample = "the quick brown fox jumps over the lazy dog";
    unique_ptr<int64_t[]> buffer = make_unique<int64_t[]>(elementSize * 32);
    cout << "flow::Vector raw\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      Vector<string> vec{};
      Timer timer{};
      timer.reset();
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.pushBack(sample);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "flow::Vector reserve\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      Vector<string> vec{};
      vec.reserve(elementSize);
      Timer timer{};
      timer.reset();
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.pushBack(sample);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "flow::Vector raw arena\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      ArenaMemoryResource resource(buffer.get(), elementSize * 32 * sizeof(int64_t));
      PolymorphicAllocator<> alloc{ resource };
      Vector<string> vec{ alloc };
      Timer timer{};
      timer.reset();
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.pushBack(sample);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "flow::Vector reserve arena\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      ArenaMemoryResource resource(buffer.get(), elementSize * 32 * sizeof(int64_t));
      PolymorphicAllocator<> alloc{ resource };
      Vector<string> vec{ alloc };
      vec.reserve(elementSize);
      Timer timer{};
      timer.reset();
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.pushBack(sample);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
  }
References flow::Vector< T, Allocator, Strategy >::pushBack(), flow::Timer< ClockType >::record(), flow::Vector< T, Allocator, Strategy >::reserve(), flow::Timer< ClockType >::reset(), and flow::Timer< ClockType >::toString().
benchmarkStdSet()
void benchmark::benchmarkStdSet (std::size_t elementSize, std::size_t benchTime) inline
Definition at line 280 of file benchmark.h.
{
    using namespace std;
    using namespace flow;
    unique_ptr<byte[]> buffer = make_unique<byte[]>(elementSize * sizeof(int64_t) * 32);
    vector<int64_t> nums(elementSize);
    iota(nums.begin(), nums.end(), int64_t(0));
    flow::shuffle(nums.begin(), nums.end());
    cout << "std::set\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      set<int64_t, std::less<int64_t>> st{};
      Timer timer{};
      timer.reset();
      for (auto n : nums) {
        st.insert(n);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "std::set arena\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      ArenaMemoryResource resource(buffer.get(), elementSize * sizeof(int64_t) * 32);
      PolymorphicAllocator<> alloc{ resource };
      set<int64_t, std::less<int64_t>, PolymorphicAllocator<int64_t>> st{ alloc };
      Timer timer{};
      timer.reset();
      for (auto n : nums) {
        st.insert(n);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "std::set monotonic\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      std::pmr::monotonic_buffer_resource mbr{ buffer.get(), elementSize * sizeof(int64_t) * 32 };
      std::pmr::polymorphic_allocator<int64_t> pa{ &mbr };
      pmr::set<int64_t, std::less<int64_t>> st(pa);
      Timer timer{};
      timer.reset();
      for (auto n : nums) {
        st.insert(n);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
  }
References flow::Timer< ClockType >::record(), flow::Timer< ClockType >::reset(), flow::shuffle(), and flow::Timer< ClockType >::toString().
benchmarkStdVector()
void benchmark::benchmarkStdVector (std::size_t elementSize, std::size_t benchTime) inline
Definition at line 17 of file benchmark.h.
{
    using namespace std;
    using namespace flow;
    unique_ptr<int64_t[]> buffer = make_unique<int64_t[]>(elementSize * 32);
    cout << "std::vector raw\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      vector<int64_t> vec{};
      Timer timer{};
      timer.reset();
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.push_back(i);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "std::vector reserve\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      vector<int64_t> vec{};
      Timer timer{};
      timer.reset();
      vec.reserve(elementSize);
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.push_back(i);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "std::vector raw arena\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      ArenaMemoryResource resource(buffer.get(), elementSize * 32 * sizeof(int64_t));
      PolymorphicAllocator<> alloc{ resource };
      vector<int64_t, PolymorphicAllocator<int64_t>> vec{ alloc };
      Timer timer{};
      timer.reset();
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.push_back(i);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "std::vector reserve arena\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      ArenaMemoryResource resource(buffer.get(), elementSize * 32 * sizeof(int64_t));
      PolymorphicAllocator<> alloc{ resource };
      vector<int64_t, PolymorphicAllocator<int64_t>> vec{ alloc };
      Timer timer{};
      timer.reset();
      vec.reserve(elementSize);
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.push_back(i);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
  }
References flow::Timer< ClockType >::record(), flow::Timer< ClockType >::reset(), and flow::Timer< ClockType >::toString().
benchmarkStdVectorString()
void benchmark::benchmarkStdVectorString (std::size_t elementSize, std::size_t benchTime) inline
Definition at line 148 of file benchmark.h.
{
    using namespace std;
    using namespace flow;
    const string sample = "the quick brown fox jumps over the lazy dog";
    unique_ptr<int64_t[]> buffer = make_unique<int64_t[]>(elementSize * 32);
    cout << "std::vector raw\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      vector<string> vec{};
      Timer timer{};
      timer.reset();
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.push_back(sample);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "std::vector reserve\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      vector<string> vec{};
      vec.reserve(elementSize);
      Timer timer{};
      timer.reset();
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.push_back(sample);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "std::vector raw arena\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      ArenaMemoryResource resource(buffer.get(), elementSize * 32 * sizeof(int64_t));
      PolymorphicAllocator<> alloc{ resource };
      vector<string, PolymorphicAllocator<string>> vec{ alloc };
      Timer timer{};
      timer.reset();
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.push_back(sample);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
    cout << "std::vector reserve arena\n";
    for (std::size_t bench = 0; bench < benchTime; ++bench) {
      ArenaMemoryResource resource(buffer.get(), elementSize * 32 * sizeof(int64_t));
      PolymorphicAllocator<> alloc{ resource };
      vector<string, PolymorphicAllocator<string>> vec{ alloc };
      vec.reserve(elementSize);
      Timer timer{};
      timer.reset();
      for (std::size_t i = 0; i < elementSize; ++i) {
        vec.push_back(sample);
      }
      timer.record();
      cout << timer.toString() << '\n';
    }
  }
References flow::Timer< ClockType >::record(), flow::Timer< ClockType >::reset(), and flow::Timer< ClockType >::toString().