Flow: RandomMeldableHeap< T, Predicate >::Node Struct Reference
RandomMeldableHeap< T, Predicate >::Node Struct Reference
Public Member Functions
Node (T &&val)
Node (const Node &)=delete
Node (Node &&)=delete
Node & operator= (const Node &)=delete
Node & operator= (Node &&)=delete
~Node ()
Public Attributes
T val_
Node * left_
Node * right_
Detailed Description
template<typename T, typename Predicate = std::greater<T>>
struct RandomMeldableHeap< T, Predicate >::Node
Definition at line 9 of file RandomMeldableHeap.h.
Constructor & Destructor Documentation
Node() [1/3]
template<typename T, typename Predicate = std::greater<T>> RandomMeldableHeap< T, Predicate >::Node::Node (T && val) inline
Definition at line 14 of file RandomMeldableHeap.h.
: val_(std::move(val)), left_(), right_() {}
References left_, right_, and val_.
Referenced by Node(), Node(), operator=(), and operator=().
Node() [2/3]
template<typename T, typename Predicate = std::greater<T>> RandomMeldableHeap< T, Predicate >::Node::Node (const Node &) delete
References Node().
Node() [3/3]
template<typename T, typename Predicate = std::greater<T>> RandomMeldableHeap< T, Predicate >::Node::Node (Node &&) delete
References Node().
~Node()
template<typename T, typename Predicate = std::greater<T>> RandomMeldableHeap< T, Predicate >::Node::~Node () inline
Definition at line 19 of file RandomMeldableHeap.h.
            {
      delete left_;
      delete right_;
    }
References left_, and right_.
Member Function Documentation
operator=() [1/2]
template<typename T, typename Predicate = std::greater<T>> Node & RandomMeldableHeap< T, Predicate >::Node::operator= (const Node &) delete
References Node().
operator=() [2/2]
template<typename T, typename Predicate = std::greater<T>> Node & RandomMeldableHeap< T, Predicate >::Node::operator= (Node &&) delete
References Node().
Member Data Documentation
left_
template<typename T, typename Predicate = std::greater<T>> Node* RandomMeldableHeap< T, Predicate >::Node::left_
Definition at line 11 of file RandomMeldableHeap.h.
Referenced by RandomMeldableHeap< T, Predicate >::MergeRoots(), Node(), RandomMeldableHeap< T, Predicate >::Pop(), and ~Node().
right_
template<typename T, typename Predicate = std::greater<T>> Node* RandomMeldableHeap< T, Predicate >::Node::right_
Definition at line 12 of file RandomMeldableHeap.h.
Referenced by RandomMeldableHeap< T, Predicate >::MergeRoots(), Node(), RandomMeldableHeap< T, Predicate >::Pop(), and ~Node().
val_
template<typename T, typename Predicate = std::greater<T>> T RandomMeldableHeap< T, Predicate >::Node::val_
Definition at line 10 of file RandomMeldableHeap.h.
Referenced by RandomMeldableHeap< T, Predicate >::MergeRoots(), and Node().
The documentation for this struct was generated from the following file:
RandomMeldableHeap.h